fribbels/hsr-optimizer

src/components/ImportTab.js, src/components/OptimizerForm.js, src/lib/db.js, src/lib/defaultForm.js, src/lib/ocrParserKelz3.js
The code quality of this pr is a tad dubious, but it works for me, and I thought I'd share it upstream in case it's helpful / alleviates any extra work for you. I'm also defaulting light-cones to `{key: 'Multiplication', level: 80, superimposition: 5}` if they don't have one since putting an undefined ID breaks things...
=> Add character importing for Kel-Z scanner

.github/issue_template.md, .github/pull_request_template.md
This PR creates a template for new PRs and issues.
No issue related
- Added `pull_request_template.md` file to `.github` folder
- Added `issue_template.md` file to `.github` folder
PR Template
Issue Template
- This must be merged into the default branch `main` to take effect in the repository. As we will be doing a near beta merge into main, this change will also be applied there.
=> chore: PR and issue templates

src/components/RelicModal.js
=> Refactor truncate10ths function in RelicModal.js

src/lib/db.js
This reverts one of the changes that #68 done.
#68 
- Included characterGrid redrawRows when deleting relics to update characters color coding.
=> Hotfix: Character equipped relics color coding refresh

src/components/common/ColorizeNumbers.tsx
fix(common): adding a unique key to the render branch to satisfy react requirements for peer FCs
=> Fix: console warnings when rendering common WithPopover mixins

src/types/Character.d.ts, src/types/CharacterConditional.d.ts, src/types/Relic.d.ts
merges into /beta stomped some type remaps
fixes: npm run typecheck
=> chore(ts): fix types from merge

src/components/OptimizerForm.jsx, src/components/optimizerForm/RecommendedPresetsButton.tsx, src/components/optimizerForm/SetsOptions.tsx, src/lib/constants.ts, src/lib/db.js, src/lib/optimizer.js, src/lib/relicFilters.js
* Moved the relic set options into constants
* Fixing dead options on profile load 
#127
=> fix: dead set options

src/components/MenuDrawer.jsx
* Fixing optimizer tab switches not updating permutations
=> fix: optimizer permutations not updating

src/App.jsx, src/components/ChangelogTab.tsx, src/components/CharacterTab.jsx, src/components/RelicsTab.jsx, src/components/optimizerTab/OptimizerGrid.jsx, src/components/optimizerTab/constants.ts, src/lib/arrowKeyGridNavigation.ts, src/lib/constants.ts, src/lib/dataParser.js, src/lib/db.js, src/lib/defaultForm.js, src/lib/optimizerTabController.js, src/style/style.css
* Some minor visual changes
* Added arrow key navigation on grids
* Stat display is now default, and saves correctly
=> feat: arrow key navigation, fix saving stat display, make combat default

src/components/RelicsTab.jsx, src/components/optimizerTab/constants.ts, src/lib/gradient.js, src/lib/optimizer.js, tests/RelicModal/3-edit-from-relics-tab.spec.ts, tests/RelicsTab/delete-relic.spec.ts
* Added CV column on relics tab
* Fixed grade/rarity filter
=> feat: relics tab cv, fix grade filter

.github/pull_request_template.md, CONTRIBUTING.md, src/components/CharacterTab.jsx, src/components/OptimizerForm.jsx, src/components/RelicModal.jsx, src/components/optimizerTab/OptimizerOptions.tsx, src/lib/db.js, src/lib/hint.jsx, src/lib/optimizer/optimizer.js, src/lib/optimizerTabController.js, src/lib/relicFilters.js, tests/RelicModal/2-edit-from-character-preview-tab.spec.ts, tests/RelicModal/3-edit-from-relics-tab.spec.ts, tests/RelicsTab/add-new-relic.spec.ts
* Added a "Move to top" button on the characters page
* Added new filter options
* Priority changes the priority on the character page & sets filters
* Exclude overrides priority and additionally excludes selected characters
* Updates to PR template
* https://github.com/fribbels/hsr-optimizer/issues/150
=> feat: priority selector, exclude filter, move to top button

src/components/GettingStartedTab.jsx, src/lib/conditionals/character/Aventurine.ts
* Aventurine beta changes
* Fix getting started info
#120
=> feat: 2.1 beta updates

src/lib/worker/optimizerWorker.js
* Fix ehp filter
* https://github.com/fribbels/hsr-optimizer/issues/176
=> fix: ehp filter

src/components/Tabs.jsx, src/components/optimizerTab/OptimizerForm.jsx, src/components/optimizerTab/OptimizerSuggestionsModal.tsx, src/components/optimizerTab/OptimizerTab.jsx, src/lib/db.js, src/lib/message.js, src/lib/optimizer/optimizer.js, src/lib/optimizerTabController.js
* Added a new modal which detects potential issues for why the optimization search results in 0 permutations
* The modal suggests potential fixes and applies them on click
* Added a permutations refresh when navigating to optimizer tab
* Added on-click close for messages
* #169
=> feat: zero permutations suggestions modal

src/App.jsx, src/components/CharacterModal.jsx, src/components/RelicFilterBar.jsx, src/components/ScoringModal.jsx, src/components/optimizerTab/optimizerForm/CharacterSelect.tsx, src/components/optimizerTab/optimizerForm/CharacterSelectorDisplay.tsx, src/components/optimizerTab/optimizerForm/LightConeSelect.tsx, src/components/optimizerTab/optimizerForm/TeammateCard.tsx, src/lib/optimizerTabController.js
* Added the new character selects to relic tab, scoring modal, character tab, teammates, etc
* Adjusted some selector styles
* Reset animations to default speeds, fast animations were causing visual bugs
* N/A
=> feat: apply char/lc selectors everywhere, tweak styles

src/components/CharacterTab.jsx, src/components/RelicModal.jsx, src/components/SwitchRelicsModal.jsx, src/components/optimizerTab/optimizerForm/OptimizerOptionsDisplay.tsx, src/lib/db.js, src/lib/utils.js, tests/CharacterPreview/switch-relics-with-character.spec.ts
* Added a new character tab action item "Switch relics with" that switches relics between the currently selected character and the character selected in the modal.
* Added a Utils function to generate a selection of the current characters (listed in the Characters tab) as opposed to all characters.
* Refactored places where this selection is needed to use this new Util ([RelicModal](https://github.com/reveritas/hsr-optimizer/blob/feature/172-swap-relics/src/components/RelicModal.jsx) when adding or editing a relic anywhere, and [OptimizerOptionsDisplay](https://github.com/reveritas/hsr-optimizer/blob/feature/172-swap-relics/src/components/optimizerTab/optimizerForm/OptimizerOptionsDisplay.tsx) in the Exclude selection).
* With the latter, I also removed the currently selected character in …
=> feat: "switch relics with" modal

src/components/RelicsTab.jsx
=> fix: use '80%+' for buckets rather than '80-90'

src/components/GettingStartedTab.jsx, src/components/importerTab/ScannerImportSubmenu.tsx, src/components/optimizerTab/optimizerForm/LightConeSelect.tsx, src/components/optimizerTab/optimizerForm/RecommendedPresetsButton.tsx, src/components/optimizerTab/optimizerForm/RelicMainSetFilters.tsx, src/lib/dataParser.js, src/lib/db.js, src/lib/hint.jsx, src/lib/importer/importConfig.js, src/lib/optimizerTabController.js
=> Merge main into beta

src/components/CharacterPreview.jsx, src/components/EditImageModal.tsx, src/lib/conditionals/lightcone/4star/PlanetaryRendezvous.ts, src/types/CustomImage.d.ts
* Add artist name input to the "Edit crop" modal screen
* Add artist name display to the custom portrait
* Fix Planetary Rendezvous lc teammate view missing
* N/A
=> feat: add artist name input and display for custom portrait

src/components/CharacterTab.jsx
* Added "Sort all characters by score" button to the character actions menu.
* This is primarily useful for first import as an initial sort, as generally the characters you care about the most are usually the most well built :)
* I don't think there's an existing issue for this
=> feat: sort characters by score

src/lib/assets.js, src/lib/optimizer/calculateStats.js
* Replaced all assets with compressed webp versions for faster loading
* Fixed bug on empty slot optimization
* https://github.com/fribbels/hsr-optimizer/issues/168
=> feat: smaller image sizes

misc/betaCharacterGenerator.ts, misc/betaLightConeGenerator.ts, src/components/RelicScorerTab.jsx, src/components/importerTab/ScannerImportSubmenu.tsx, src/data/characters.json, src/data/light_cones.json, src/index.jsx, src/lib/dataParser.js
* Added a new site https://starrailoptimizer.github.io/ for leaks-free optimizer
* Added "unreleased" flag into character files
* Added window.officialOnly = false global flag which is overriden by gh actions 
* Put unreleased characters and reliquary behind the officialOnly flag
* #272
=> feat: initial implementation for leak free optimizer version

src/components/BuildsModal.tsx
* The score in saved builds shows the updated score wrt the current user-set scoring algorithm 
Tried to follow surrounding code format (eg passing build name instead of build directly in the db file)
* Fixes #170
Here's a video of the updated functionality!
https://github.com/fribbels/hsr-optimizer/assets/59471320/aa53c38f-9e09-4cb5-92dc-8a314ddd4d6a
=> fix(#170):update build scores when saved build modal opens

.github/workflows/starrailoptimizer.yml, src/components/CharacterModal.jsx, src/components/CharacterPreview.jsx, src/components/EditImageModal.tsx, src/components/RelicFilterBar.jsx, src/components/importerTab/ScannerImportSubmenu.tsx, src/components/optimizerTab/OptimizerForm.jsx, src/components/optimizerTab/optimizerForm/CharacterSelect.tsx, src/components/optimizerTab/optimizerForm/RelicMainSetFilters.tsx, src/lib/db.js, src/lib/optimizerTabController.js
* Removing unnecessary level selectors for characters / lcs
* Fix a bug where switching characters resets the lc conditional to default
* Fix firefox custom characters modal closing
* Artist name adjustments
* Fix starrailoptimizer assets path
* #286
=> fix: remove character level selectors / other bug fixes

src/lib/conditionals/character/Boothill.ts, src/lib/conditionals/character/Robin.ts, src/lib/conditionals/character/TrailblazerHarmony.ts, src/lib/conditionals/conditionalConstants.ts, src/lib/optimizer/calculateDamage.js, src/types/Conditionals.d.ts
* Updated with beta v4 changes
* Changed Robin's trace to FUA Crit DMG vulnerability + added to damage formula
*
=> hotfix: 2.2v4 beta changes

src/lib/conditionals/character/Robin.ts, src/lib/conditionals/conditionalConstants.ts, src/lib/optimizer/calculateDamage.js, src/types/Conditionals.d.ts
* Fixing a double stacked CD buff
* Change vulnerability back to FUA CD buff
*
=> hotfix: edit robin buffs

src/components/MenuDrawer.jsx, src/index.jsx
* Found a bug where the officialOnly flag was still false at the time of menu creation, putting it in a memo
*
=> fix: load menu in a memo so officialOnly flag is set

src/lib/characterConverter.ts
* Discovered that it also has a special main stat mapping, now correctly shows as heal boost
*
=> hotfix: special relic main stat mapping

src/App.jsx, src/components/optimizerTab/OptimizerForm.jsx, src/components/optimizerTab/optimizerForm/DamageCalculatorDisplay.tsx, src/components/optimizerTab/optimizerForm/SimulatedBuildsGrid.tsx, src/lib/db.js, src/lib/defaultForm.js, src/lib/statCalculator.js, src/lib/statSimulationController.tsx
* Removed the character-stats sim placeholder
* Added substat-roll sim
* Various ui tweaks for the sim row
*
=> feature: substat roll simulator

src/components/CharacterPreview.jsx, src/components/optimizerTab/conditionals/FormSlider.tsx, src/components/optimizerTab/optimizerForm/RecommendedPresetsButton.tsx, src/components/optimizerTab/optimizerForm/StatSimulationDisplay.tsx, src/lib/db.js, src/lib/optimizerTabController.js, src/style/style.css
* Various UI tweaks
* Use the custom scoring overrides when selecting presets
* Apply scoring metadata weights and main stats to new selected characters
* Save custom portraits from the relic scorer
* #316 
* #312 
* #265
=> feat: save custom portraits from relic scorer, apply scoring overrides to presets and presets to new characters

src/components/optimizerTab/optimizerForm/RecommendedPresetsButton.tsx, src/lib/defaultForm.js, src/lib/optimizerTabController.js
* Patching a bug where substat weights were being overridden. Moving the logic to the default form but this should probably be cleaned up eventually
* fixes #331
=> hotfix: character weights and filter options not saving

backend/infra.ts, backend/package-lock.json, backend/package.json, src/components/RelicScorerTab.jsx
- hotfix: apply relic scorer backup logic for new patche
- docs: infra commands
* 
*
=> hotfix: add a backup option to the relic scorer for new patches

backend/infra.ts, backend/package-lock.json, backend/package.json, src/components/RelicScorerTab.jsx, src/lib/optimizerTabController.js
* There was a bug where overwriting metadata was causing a cyclic reference instead of using scoring metadata, resolving the bug
*
=> hotfix: bug with metadata being ovewritten incorrectly

src/lib/importer/importConfig.js
* Adding the Yas scanner as a prerelease option
* Will update more details and a UI slot on the Import tab, after the scanner gets officially released
* This will make the scanner available at https://fribbels.github.io/dreary-quibbles/
* #327
=> feat: add yas scanner prerelease option

src/components/importerTab/ReliquaryDescription.tsx
* Temp disable reliquary while keys are down
*
=> hotfix: changing reliquary to off for now

src/lib/characterScorer.ts, src/lib/dataParser.js
* Sim scoring for bs kafka blade seele jade boothill with some estimated rotations
* Added BREAK column formula
* N/A
=> feat: bs kafka blade seele jade boothill sim scorings

src/components/importerTab/ReliquaryDescription.tsx, src/lib/importer/importConfig.js
=> Bump reliquary archiver version to v0.1.6

src/components/RelicModal.jsx, tests/RelicsTab/add-new-relic.spec.ts
* Partial change to 251, adding +3 enhance button to speed up relic editing.
* #251
=> Enhance +3 button in relic edit modal

src/lib/characterScorer.ts, src/lib/dataParser.js
* New formula (current - base) / (ideal - base)
* New score characters: xueyi jingyuan himeko clara qingque
*
=> feat: scoring baseline + xueyi jingyuan himeko clara qingque

src/components/CharacterPreview.jsx, src/lib/characterScorer.ts, src/lib/dataParser.js
* Adding aventurine, switch ideal to 36 subs
* Edit the scoring label
*
=> feat: 36 scoring ideal subs

src/components/CharacterPreview.jsx, src/lib/characterScorer.ts, src/lib/statCalculator.js, src/lib/statSimulationController.tsx
* Scoring unsets the min value for spd now, replaces with dps stats
* Replaced with min roll stats
*
=> feat: change scoring to 42 low rolls

src/components/CharacterPreview.jsx, src/components/CharacterTab.jsx, src/components/characterPreview/CharacterScoringSummary.tsx, src/components/characterPreview/CharacterStatSummary.tsx, src/lib/characterScorer.ts, src/lib/dataParser.js, src/lib/statSimulationController.tsx, src/lib/utils.js
* Adding a quick UI for scoring
* Set Xueyi break formula to 1
* Setting boothill ornament set to talia
*
=> feat: initial simulation scoring ui implementation

src/lib/statSimulationController.tsx
* Fixing a bug where empty sets were being detected as Space Sealing Station for the stat simulator
* Fixing a bug where missing statSim caused errors when clicking optimizer rows
*
=> fix: bug in SSS set detection

src/components/characterPreview/CharacterScoringSummary.tsx, src/lib/characterScorer.ts, src/lib/dataParser.js, src/lib/statSimulationController.tsx
* Changed the substat selection method to 6 stat priority
* DHIL gets 4p musketeer
* Add substat upgrade summary
*
=> feat: 6 stat priority scoring, substat upgrade summary

src/components/CharacterPreview.jsx, src/lib/characterScorer.ts, src/lib/dataParser.js
* Fixed lc centering issues with the new card format. 
*
=> feat: recenter all light cones for new character card format

src/lib/characterScorer.ts
=> feat: 54 goal / 0.8 quality / 2 free rolls

src/lib/characterScorer.ts, src/lib/conditionals/character/Sparkle.ts
=> feat: 50 goal / 0.8 quality / 2 free rolls, sparkle skill fix

src/lib/conditionals/character/Firefly.ts
* Fix e1 def shred applying to break dmg
*
=> fix: firefly e1 def shred

src/components/CharacterPreview.jsx, src/components/characterPreview/CharacterScoringSummary.tsx, src/lib/characterScorer.ts, src/lib/dataParser.js
- feat: making sims faster
- feat: add smarter substat selection, remove useless BE
Previously every character had BE, but we only really need it when BREAK is in the formula or HMC is on the team
*
=> hotfix: fix some sim lag

src/components/CharacterPreview.jsx
* Fixing a bug where the TBD label was appearing with the wrong trigger
*
=> hotfix: bug with the scoring TBD label

src/components/CharacterPreview.jsx
* Fix the scoring text doing a line break
* Fix missing default scoring type
*
=> hotfix: fix score breaking line, add a default scoring type

src/components/HeaderText.jsx
* Hotfixing a UI issue where header text was wrapping
*
=> hotfix: header text was wrapping

src/components/CharacterPreview.jsx, src/components/characterPreview/CharacterScoringSummary.tsx, src/lib/characterScorer.ts, src/lib/dataParser.js, src/lib/db.js, src/lib/optimizerTabController.js, src/lib/statSimulationController.tsx
* Smaller lc height
* Combat sim text
* 54 min rolls, 3 free, grading buff
* Fix baselining
*
=> feat: fix baselining, buff scores a bit

src/components/CharacterPreview.jsx, src/components/characterPreview/CharacterScoringSummary.tsx, src/lib/characterScorer.ts, src/lib/dataParser.js, src/lib/db.js, src/lib/optimizerTabController.js, src/lib/statSimulationController.tsx
* Made various scoring updates, fixed baselining
*
=> hotfix: combat scoring adjustments

src/lib/conditionals/character/Aventurine.ts, src/lib/optimizer/calculateBuild.js, src/lib/optimizer/calculateDamage.js, src/lib/optimizer/calculateStats.js, src/lib/worker/optimizerWorker.js, src/types/Conditionals.d.ts
* Reverting the previous fix, applying a more targetted approach using the calculatePassives field that was meant for this purpose
*
=> hotfix: new way to deal with incorrect set activation

src/components/CharacterPreview.jsx, src/components/Dividers.tsx, src/components/characterPreview/CharacterScoringSummary.tsx, src/lib/TsUtils.ts, src/lib/characterScorer.ts, src/lib/conditionals/lightcone/5star/SleepLikeTheDead.ts, src/lib/dataParser.js, src/lib/statSimulationController.tsx, src/types/Character.d.ts, src/types/Form.d.ts, src/types/LightCone.d.ts, src/types/Relic.d.ts
* For builds over 100%, benchmark against the 200% score build
* Typescript cleanup for sims
* Fix sleep like the dead to not apply crit buff
* Started migrating Utils to TsUtils
*
=> feat: score against 200% benchmark, simulations typescript cleanup

src/components/CharacterPreview.jsx, src/components/characterPreview/CharacterScoringSummary.tsx, src/lib/characterScorer.ts, src/lib/statSimulationController.tsx
* 200% sim is now a possible build
* Baseline with no main stats
* Adjust letter grade scales
*
=> feat: making perfect sim possible build

src/lib/conditionals/character/Boothill.ts
* fix: Boothill's standoff was incorrectly applied and DMG bonus instead of vulnerability
*
=> hotfix: boothill standoff dmg to vulnerability

src/lib/conditionals/character/Jade.ts
* Add ashblazing damage calc for jade fua
*
=> hotfix: add Jade ashblazing calcs

src/components/CharacterCustomPortrait.tsx, src/components/CharacterPreview.jsx, src/components/CharacterTab.jsx, src/components/characterPreview/CharacterScoringSummary.tsx, src/lib/constants.ts, src/lib/db.js, src/style/style.css
* Fix builds modal
* Teammate sync feature
* Settings button on teammate menu
* Fixed box shadows on safari
* Scoring analysis layout
* Added confirm messages for settings buttons
*
=> feat: scoring card ui/ux, edit character button, scoring analysis layout

src/lib/importer/hoyoLabFormatParser.tsx
* fix metadata not properly set on hoyolab import
*
=> fix metadata

src/components/RelicModal.tsx, src/types/Relic.d.ts
* Removes verified status from relics when edited
* Closes #224
=> fix: editing verified relics

src/components/RelicsTab.jsx
* Added a toggle to switch between selected characters and all characters in the relic insights panel(s)
* Closes #311
=> feat: toggle potential

src/components/CharacterPreview.jsx, src/components/characterPreview/CharacterScoringSummary.tsx, src/components/optimizerTab/optimizerForm/CombatBuffsFilters.tsx, src/lib/constants.ts, src/lib/optimizer/calculateStats.js, tests/CharacterPreview/edit-main-stat-loads-maxed-stat.spec.ts
* Updating the custom buffs menu
* Added: HP/DEF/%
* Added: Eff res shred, vulnerability, break efficiency
* Updated dmg calcs
* Added DPS increase to score analysis
* Fix elemental damage displaying wrong on the character preview
* #384
=> feat: expanding custom buffs menu

src/components/ScoringModal.jsx
* Added the normalization for effect res to the scoring algorithm explanation
*
=> chore: add effect res normalization

src/components/RelicFilterBar.jsx, src/components/RelicsTab.jsx, src/components/characterPreview/CharacterScoringSummary.tsx, src/components/optimizerTab/OptimizerForm.jsx, src/components/optimizerTab/conditionals/FormSlider.tsx, src/components/optimizerTab/conditionals/LightConeConditionalDisplay.tsx, src/components/optimizerTab/optimizerForm/ComboFilter.tsx, src/lib/characterScorer.ts, src/lib/conditionals/character/Firefly.ts, src/lib/conditionals/character/Herta.ts, src/lib/conditionals/character/Lynx.ts, src/lib/conditionals/character/RuanMei.ts, src/lib/conditionals/conditionalConstants.ts, src/lib/dataParser.js, src/lib/db.js, src/lib/hint.jsx
* Fix bug with scoring algorithm character being used for relics tab character
* Changing DPS score improvements -> Damage improvements
* Firefly BiS set to new relics
* Turn Herta technique buff off by default
* Fix Ruan Mei E2 interaction with firefly, un-fix Lynx
*
=> feature: dps improvements -> damage improvements, ui tweaks, firefly BIS configs, some bug fixes

src/lib/relicModalController.ts
* Added a check to ensure the enhance is possible for the selected grade
*
=> fix: add check for impossible grade-enhance pairing

src/components/RelicsTab.jsx, src/style/style.css
* Added display for total relic count and filtered relic count
* Closes #424
=> feat: relic count

src/components/optimizerTab/optimizerForm/OptimizerOptionsDisplay.tsx, src/lib/dataParser.js, src/style/style.css
* Highlight optimizer column when sorted
* Remove Fire DMG from firefly mains
*
=> feat: highlight sorted optimizer column, fix firefly main stats

src/components/RelicScorerTab.jsx, src/components/importerTab/ReliquaryDescription.tsx, src/lib/conditionals/character/March7thImaginary.ts, src/types/Conditionals.d.ts
* hotfix: march 8th conditionals
* fix: reliquary description
* fix: relic scorer banner
*
=> hotfix: march 8th conditional correction, add maintenance notices

backend/lambdas/get-profile.ts, src/components/RelicScorerTab.jsx, src/index.jsx, src/lib/mihomoCharacterConverter.ts
* Switching relic APIs, adding new parser
*
=> feat: add relic api replacement

backend/infra.ts, backend/lambdas/get-profile.ts, src/components/RelicScorerTab.jsx
* Adding a backup option for the relic scorer api, and adjusting the ui side to handle it
*
=> hotfix: relic scorer api backup

src/lib/importer/importConfig.js
=> Bump RQA version to be v0.1.7

src/lib/conditionals/character/Aventurine.ts, src/lib/conditionals/character/Firefly.ts, src/lib/conditionals/character/Jade.ts, src/lib/conditionals/character/TrailblazerHarmony.ts, src/lib/conditionals/lightcone/4star/AfterTheCharmonyFall.ts, src/lib/conditionals/lightcone/5star/EternalCalculus.ts, src/lib/conditionals/lightcone/5star/FlowingNightglow.ts, src/lib/conditionals/lightcone/5star/SailingTowardsASecondLife.ts, src/lib/conditionals/lightcone/5star/WhereaboutsShouldDreamsRest.ts, src/lib/conditionals/lightcone/5star/YetHopeIsPriceless.ts, src/lib/constants.ts, src/lib/db.js
- feat: update skill conditionals hover content
- fix: aventurine unnerved conditional
* https://github.com/fribbels/hsr-optimizer/issues/456
=> hotfix: aventurine missing cd conditional, update 2.3 character conditional content

src/lib/characterScorer.ts, src/lib/conditionals/character/Yunli.ts
* Buffing diminishing returns rate for 100% scoring
* New diminishing returns kicks in at 12 - 2 * mains instead of 18 - 3 * mains
```
Rolls: 0 --> Old 0.00 --> New: 0.00 --> Delta: 0.00
Rolls: 1 --> Old 1.00 --> New: 1.00 --> Delta: 0.00
Rolls: 2 --> Old 2.00 --> New: 2.00 --> Delta: 0.00
Rolls: 3 --> Old 3.00 --> New: 3.00 --> Delta: 0.00
Rolls: 4 --> Old 4.00 --> New: 4.00 --> Delta: 0.00
Rolls: 5 --> Old 5.00 --> New: 5.00 --> Delta: 0.00
Rolls: 6 --> Old 6.00 --> New: 6.00 --> Delta: 0.00
Rolls: 7 --> Old 7.00 --> New: 7.00 --> Delta: 0.00
Rolls: 8 --> Old 8.00 --> New: 8.00 --> Delta: 0.00
Rolls: 9 --> Old 9.00 --> New: 9.00 --> Delta: 0.00
Rolls: 10 --> Old 10.00 --> New: 10.00 --> Delta: 0.00
Rolls: 11 --> Old 11.00 --> New: 11.00 --> Delta: 0.00
Rolls: 12 --> Old 12.00 --> New: …
```
=> feat: scoring buff for diminishing returns

misc/beta/raw-data.ts, src/data/game_data.json, src/lib/conditionals/character/Jiaoqiu.ts, src/lib/conditionals/character/March7thImaginary.ts, src/lib/conditionals/character/Yunli.ts, src/lib/conditionals/lightcone/5star/ThoseManySprings.ts, src/lib/constants.ts, src/lib/dataParser.js, src/types/Conditionals.d.ts
* Beta v3 changes, March / Jiaoqiu / Yunli
*
=> feat: beta v3 changes

src/lib/conditionals/character/Jiaoqiu.ts
=> hotfix: Jiaoqiu V4 beta 48% -> 40% E1 dmg change

src/lib/conditionals/character/March7thImaginary.ts, src/lib/conditionals/character/Yunli.ts, src/lib/constants.ts
Beta v5 changes: 
* Yunli "ult" multipliers
* March "master" -> "shifu" (changed for text/title only)
*
=> feat: beta v5 changes

src/components/CharacterModal.jsx, src/components/CharacterPreview.jsx, src/components/CharacterTab.jsx, src/components/optimizerTab/optimizerForm/LightConeSelect.tsx
* fixed lc select not filtering by path on character tab
* changed eidolon and superimposition selection method to reduce number of clicks
Closes #372
=> feat: character modal improvements

src/components/RelicScorerTab.jsx, src/lib/db.js
* Renamed "mergeVerifiedRelicsWithState" to "mergePartialRelicsWithState"
* Added dropdown to import button on relic scorer tab for single/multi character import
* Closes #187
=> feat: import character from relic scorer

src/components/characterPreview/CharacterStatSummary.tsx, src/components/characterPreview/StatRow.tsx, src/lib/characterScorer.ts, src/lib/conditionals/character/Feixiao.ts, src/lib/conditionals/character/Lingsha.ts, src/lib/conditionals/character/Moze.ts
* Ashblazing calcs for 2.5 characters 
* Modified the spd boots force threshold to +36 spd
* Healing boost added to support cards
*
=> feat: update ashblazing calcs for 2.5 characters, fix ohb on support cards

src/components/characterPreview/CharacterStatSummary.tsx, src/components/characterPreview/StatRow.tsx
* Removing CV from character card
* Adding Energy Regen stat
* Closes https://github.com/fribbels/hsr-optimizer/issues/356
=> feat: remove cv from character card, add energy regen

src/components/optimizerTab/Sidebar.jsx, src/components/optimizerTab/optimizerTabConstants.ts, src/lib/hint.jsx, src/lib/optimizer/optimizer.js, src/lib/optimizerTabController.js
* Added the ability to pin builds to the optimizer grid and clear pinned builds
* Moved the progress bar on the mobileSidebar to avoid widening
* Closes #128
=> feat: pin builds

src/components/optimizerTab/OptimizerSuggestionsModal.tsx, src/components/optimizerTab/OptimizerTab.jsx, src/components/optimizerTab/Sidebar.jsx, src/components/optimizerTab/optimizerForm/RelicSetTagRenderer.tsx, src/lib/db.js, src/lib/optimizer/optimizer.js
* Added a popup for when the search yields 0 results
* Added a popup to warn the user before performing very large searches (>= 1 Billion)
* Related to #209
=> feat: better optimizer popup

GETTING_STARTED.md, package-lock.json, package.json, src/components/optimizerTab/optimizerTabConstants.ts, src/style/style.css, tests/RelicModal/3-edit-from-relics-tab.spec.ts, tests/RelicsTab/delete-relic.spec.ts
* Bumping node to 22.6.0, and various other libraries
*
=> chore: dependency updates

misc/beta/generateData.ts, src/components/importerTab/ReliquaryDescription.tsx, src/components/importerTab/ScannerImportSubmenu.tsx, src/data/game_data.json, src/lib/db.js, src/lib/importer/importConfig.js, src/lib/importer/kelzFormatParser.jsx
* Adding support for v4 format coming soon, following discussion on structure on discord
* Bump reliquary to 0.1.8
*
=> feat: update scanners with v4 format

src/components/optimizerTab/Sidebar.jsx, src/lib/optimizerTabController.js
* Fixing a bug where after the aggrid api update, the pinned row api has changed
*
=> fix: pinned api change for aggrid

src/components/RelicFilterBar.jsx, src/components/RelicsTab.jsx, src/lib/db.js, src/lib/renderer.jsx, src/types/store.ts
* Aggrid 32.1.0 introduced new filter APIs but we don't necessarily need them, changing the filters to simpler conditions
*
=> fix: simplifying relic filters to comply with new aggrid version

src/App.jsx, src/components/MenuDrawer.jsx, src/components/characterPreview/CharacterScoringSummary.tsx, src/components/characterPreview/CharacterStatSummary.tsx
* Updating menu to put relic scorer first
* Add arrows to changed combat stats menu
*
=> feat: update sidebar menu, add arrow to buffed stats

src/components/RelicModal.tsx, src/lib/relicModalController.ts
* Relic modal no longer shows NaNs for upgrades
* Fixed a string formatting issue when inputting percents
*
=> fix: relic modal bug and some input improvements

src/components/CharacterModal.jsx, src/components/characterPreview/CharacterScoringSummary.tsx, src/components/optimizerTab/optimizerForm/CharacterSelect.tsx, src/components/optimizerTab/optimizerForm/LightConeSelect.tsx, src/icons/UpArrow.jsx
* Updating stat upgrade arrow icon
* Adding light cone path icon
*
=> feat: update stat upgrade arrow icon, light cone selector path icon

eslint.config.js, src/components/RelicScorerTab.jsx
* Added a hard and soft throttle to the submit button on the relic scorer tab
* Closes #450
=> feat: throttle relic scorer submit button

backend/lambdas/get-profile.ts, src/components/RelicScorerTab.jsx, src/lib/characterConverter.ts
* adding a third relic scorer fallback for stability
*
=> hotfix: adding a third relic scorer fallback for stability

src/components/RelicsTab.jsx
=> fix: open scoring modal on character icon clicked in relic insights

src/components/RelicsTab.jsx
* Changed relic insights panel to update update displayed characters when custom character selection changes
* Closes #479
=> fix: relic insights update characters

src/components/ChangelogTab.tsx
=> hotfix: remove Moze and Feixiao from Changelog

src/components/RelicsTab.jsx
* Changed relics grid to keep row selected after editing corresponding relic
* Closes #540
=> feat: keep relic selected in grid after editing it 

src/lib/fixedSizePriorityQueue.ts, src/lib/gpu/webgpu.ts, src/lib/gpu/webgpuInternals.ts
* Rewrote the results loop to be more performant
* Reduces redundant checks and unnecessary priority queue calls
* +50% search performance increase on standard 133 speed search
*
=> feat: webgpu performance improvements

src/lib/characterScorer.ts, src/lib/optimizer/calculateBuild.js, src/lib/statSimulationController.tsx
* The character sims were generating new conditionals every run x hundreds/thousands of runs. 
* Caching params to reduce lag
*
=> feat: cache scoring sim optimizer params for better performance

src/components/CharacterPreview.jsx
* Previously when custom teammates were loaded, depending on the previously selected character's team option, the character sims may run on both custom and default teams.
* This caused a lag spike in loading character cards
* Update the team selection logic to handle all cases of the previously selected character so only one set of sims runs
*
=> feat: handle custom team selection cases for better character card performance

package-lock.json, package.json, src/components/CharacterTab.jsx, src/components/RelicScorerTab.jsx, src/components/RelicsTab.jsx, src/components/optimizerTab/Sidebar.jsx, src/index.jsx, src/lib/characterScorer.ts, src/lib/gpu/injection/generateWgsl.ts, src/lib/gpu/tests/webgpuTestGenerator.ts, src/lib/gpu/tests/webgpuTestUtils.ts, src/lib/gpu/webgpuDataTransform.ts, src/lib/gpu/webgpuDebugger.ts, src/lib/gpu/webgpuDevice.ts, src/lib/gpu/webgpuInternals.ts, src/lib/gpu/webgpuOptimizer.ts, src/lib/gpu/webgpuTypes.d.ts, src/lib/gpu/wgsl/postComputeShader.wgsl, src/lib/notifications.tsx, src/lib/optimizer/optimizer.ts, src/lib/utils.js, src/style/style.css, src/types/Form.d.ts, src/types/LightCone.d.ts, src/types/store.ts
* Switched to dom-to-image-more to render screenshots
* Added popconfirm to optimizer reset button
* Webgpu code cleanup
*
=> feat: webgpu tweaks, update screenshot library for firefox

src/components/CharacterPreview.jsx, src/lib/characterScorer.ts, src/lib/optimizer/calculateBuild.js, src/lib/statSimulationController.tsx
* Removed a couple useless clone calls in the scorer to speed it up about 2x
* Fixed a bad assumption about max crit rate rolls in the max substat roll generator
*
=> feat: improve character scoring sim speed, fix impossible max sim builds

src/components/LoadingBlurredImage.tsx, src/components/characterPreview/CharacterScoringSummary.tsx, src/lib/TsUtils.ts
* Rewrote LoadingBlurredImage to better handle state, images will now wait for load before applying styles, reducing the amount of jumping around it does
*
=> feat: better portrait loading behavior

src/lib/dataParser.js
* Updated pioneer conditionals 4x for dps characters with debuff
* Topaz Misha Aventurine Yunli Pela Serval Himeko
*
=> feat: update pioneer conditionals for debuff characters

src/components/optimizerTab/optimizerForm/CharacterSelect.tsx, src/components/optimizerTab/optimizerForm/CharacterSelectorDisplay.tsx, src/components/optimizerTab/optimizerForm/LightConeSelect.tsx, src/components/optimizerTab/optimizerForm/OptimizerTabCharacterPanel.tsx, src/components/optimizerTab/optimizerForm/TeammateCard.tsx, src/lib/db.js, src/types/store.ts
* Added ability to open respective selection modals by clicking on relevant image
* Closes #573
=> feat: open modals on image clicked

src/data/game_data.json, src/lib/conditionals/character/Rappa.ts, src/lib/constants.ts, src/lib/gpu/conditionals/dynamicConditionals.ts, src/lib/gpu/wgsl/computeShader.wgsl, src/lib/optimizer/calculateStats.ts, src/types/Conditionals.d.ts
=> hotfix: 2.6v4 content

public/locales/en/optimizerTab.json
=> update sacerdos teammate values, timer fix

public/locales/en/conditionals.json, src/types/resources.d.ts
=> fix: $ in translations

src/components/optimizerTab/OptimizerForm.jsx, src/components/optimizerTab/optimizerForm/ResultFilters.tsx
* Restoring the ratings card for now, didn't come up with a better idea for a feature to put in that slot so waiting for next patch
*
=> feat: revert filter card removal temporarily

misc/i18n/generateTranslations.ts, public/locales/en/gameData.yaml, src/lib/i18n.ts
=> feat: game data overrides

docs/guides/en/advanced-rotations.md, public/locales/en/optimizerTab.yaml, src/components/ChangelogTab.tsx, src/lib/i18n.ts, src/lib/optimizerTabController.js
* Wording changes
* Disable language detection
* Fix null optimizer grid error
*
=> fix: wording tweaks, fixes

src/components/Tabs.jsx, src/components/metadataTab/MetadataTab.tsx, src/lib/db.js
https://fribbels.github.io/dreary-quibbles/#metadata
* Adding dev debug page for scoring metadata
*
=> feat: metadata tab

src/components/metadataTab/MetadataTab.tsx, src/components/optimizerTab/optimizerForm/RecommendedPresetsButton.tsx, src/lib/defaultForm.js, src/lib/optimizer/rotation/comboDrawerController.tsx, src/lib/optimizerTabController.js
* Added conditional presets dashboard
* Fixed wastelander preset
* Refactor presets definition
* Added substat weight dashboard
*
=> feat: conditional sets presets dashboard

src/lib/worker/optimizerWorker.ts
=> hotfix: lightcone conditionals not properly evaluated

src/components/optimizerTab/optimizerForm/RecommendedPresetsButton.tsx, src/index.jsx, src/lib/dataParser.ts, src/lib/relicRollGrader.test.ts, src/types/LightCone.d.ts
* refactor: migrated dataParser to typescript
*
=> refactor: migrate dataParser to typescript

eslint.config.js, src/lib/TsUtils.ts, src/lib/characterConverter.ts, src/lib/db.ts, src/lib/importer/kelzFormatParser.tsx, src/lib/relicAugmenter.ts, src/lib/relicModalController.ts, src/lib/relicRollFixer.ts, src/lib/statCalculator.ts, src/types/Relic.d.ts, src/window.d.ts
* Overall typescript migration project
*
=> refactor: typescript relicAugmenter relicRollFixer statCalculator relicModalController

src/components/importerTab/ScannerImportSubmenu.tsx, src/components/optimizerTab/optimizerTabConstants.ts
=> fix: translate import placeholder

public/locales/en/charactersTab.yaml, public/locales/en/common.yaml, public/locales/en/importSaveTab.yaml, public/locales/en/modals.yaml, public/locales/en/notifications.yaml, public/locales/en/optimizerTab.yaml, public/locales/en/relicScorerTab.yaml, public/locales/en/relicsTab.yaml, public/locales/en/sidebar.yaml, public/locales/readme.md, src/components/CharacterPreview.jsx, src/components/LayoutHeader.tsx, src/components/RelicModal.tsx, src/components/RelicPreview.tsx, src/components/RelicsTab.jsx, src/components/importerTab/ClearDataSubmenu.tsx, src/components/importerTab/ScannerImportSubmenu.tsx, src/components/optimizerTab/optimizerForm/ComboFilter.tsx, src/components/optimizerTab/optimizerForm/SetsOptions.tsx, src/components/optimizerTab/rotation/ComboDrawer.tsx, src/lib/i18n.ts, src/types/resources.d.ts
* Updates translations for advanced combo
* remove unnecessary $t uses
* deprecated capitalizeString post-processor
* TODO: relic/planar tooltips still need to be migrated to setConditionalContent from FormSetConditionals
*
=> feat: advanced combo translations

public/locales/en/charactersTab.yaml, public/locales/en/common.yaml, public/locales/en/getStartedTab.yaml, public/locales/en/importSaveTab.yaml, public/locales/en/modals.yaml, public/locales/en/optimizerTab.yaml, public/locales/en/relicScorerTab.yaml, public/locales/en/relicsTab.yaml, src/components/BuildsModal.tsx, src/components/CharacterModal.tsx, src/components/CharacterTab.jsx, src/components/EditImageModal.tsx, src/components/GettingStartedTab.tsx, src/components/RelicScorerTab.jsx, src/components/SaveBuildModal.tsx, src/components/ScoringModal.tsx, src/components/SwitchRelicsModal.tsx, src/components/characterPreview/CharacterScoringSummary.tsx, src/components/optimizerTab/Sidebar.jsx, src/components/optimizerTab/optimizerForm/ComboFilter.tsx, src/components/optimizerTab/optimizerForm/StatSimulationDisplay.tsx, src/types/resources.d.ts
remove unused/unnecessary keys
* fix unquoted "Yes" and "No" in common.yaml
* remove unnecessary keys in other namespaces in favour of directly referencing the common namespace
*
=> fix: quotes around "Yes" and "No" in common ns

src/lib/conditionals/character/Clara.ts
* add missing ult dmg reduction value to Clara conditional
*
=> fix: add ult dmg reduction value to Clara conditional

public/locales/en/conditionals.yaml, src/lib/conditionals/character/Rappa.ts, src/lib/conditionals/lightcone/4star/NinjaRecordSoundHunt.ts, src/types/resources.d.ts
* Added conditionals for "Rappa" and "Ninja Record: Sound Hunt"
*
=> feat: 2.6 conditionals

src/components/LanguageSelector.tsx, src/lib/i18n.ts
* Added chinese and portuguese to the completed languages (removes the "(WIP)" suffix)
*
=> feat: add chinese and portuguese to completed languages

src/data/game_data.json, src/lib/conditionals/character/Fugue.ts, src/lib/conditionals/character/Sunday.ts, src/lib/constants.ts, src/lib/dataParser.js, src/types/Conditionals.d.ts
=> feat: 2.7v3 update

public/locales/en/optimizerTab.yaml, src/components/CharacterPreview.jsx, src/components/LayoutHeader.tsx, src/components/optimizerTab/optimizerForm/CharacterSelectorDisplay.tsx, src/components/optimizerTab/optimizerForm/FormStatRollSlider.tsx, src/components/optimizerTab/optimizerForm/RelicMainSetFilters.tsx, src/components/optimizerTab/optimizerForm/SetsOptions.tsx, src/components/optimizerTab/optimizerForm/SubstatWeightFilters.tsx, src/lib/constants.ts, src/lib/i18n.ts, src/types/resources.d.ts
* Added missing translations for optimiser tab
* Modified stat weight sliders and E/S placeholders to adjust width as necessary
*
=> fix: missing translations

.github/workflows/playwright.yml, src/components/optimizerTab/optimizerForm/FormStatRollSlider.tsx, src/lib/optimizer/calculateStats.ts
* GH actions wasnt running
* Fixed empty relic on scorer bug
*
=> fix: gh actions, relic scorer bug

src/components/CharacterPreview.jsx
* Safari was acting weird, portrait needed a display relative attribute
*
=> fix: broken portrait on safari

src/components/CharacterPreview.jsx
* Fixes offset for artist name display
*
=> fix: show artist name

src/lib/relics/relicScorerPotential.ts, src/lib/utils/arrayUtils.ts, src/lib/utils/utils.js
* Fixed the best upgraded stats not displaying added stats in non-english
*
=> fix: best upgraded added stats not properly calculated in non-english

src/lib/conditionals/character/Fugue.ts, src/lib/conditionals/character/Sunday.ts, src/lib/conditionals/lightcone/5star/LongRoadLeadsHome.ts, src/lib/constants.ts
=> feat: 2.7v5 updates

public/locales/en/hint.yaml, src/lib/interactions/hint.tsx, src/lib/tabs/tabOptimizer/optimizerForm/components/EnemyConfigurationsDrawer.tsx, src/types/resources.d.ts
* Cleanup hint text
* Added "max toughness" to toughness selector
*
=> fix: cleanup hint text

public/locales/en/conditionals.yaml, src/lib/conditionals/character/1200/Fugue.ts, src/lib/conditionals/character/1300/Sunday.ts, src/lib/conditionals/lightcone/5star/AGroundedAscent.ts, src/lib/conditionals/lightcone/5star/LongRoadLeadsHome.ts, src/types/resources.d.ts
* Added conditional translation for Fugue, Sunday, Long Road Leads Home, and A Grounded Ascent
* Renamed Fugue's break threshold conditional from `be250Buff` to `be220Buff`
*
=> feat: translation support for 2.6 conditionals

src/App.tsx, src/lib/characterPreview/ShowcaseCustomizationSidebar.tsx, src/lib/characterPreview/ShowcaseLightCone.tsx, src/lib/characterPreview/StatText.tsx, src/lib/overlays/modals/EditImageModal.tsx, src/lib/overlays/modals/ScoringModal.tsx, src/lib/rendering/theme.ts, src/lib/tabs/tabShowcase/RelicScorerTab.jsx, src/lib/utils/colorUtils.ts
* Update color generation code
* Fix showcase upload
* Fix showcase segmented rendering
*
=> feat: showcase color adjustments, various relic scorer fixes

src/lib/constants/constants.ts, src/lib/tabs/tabOptimizer/optimizerForm/optimizerFormTransform.ts, src/types/form.d.ts
* Fixed optimiser form crashing when selecting teammates without having a character selected for optimisation
*
=> fix: optimizer form crash

public/locales/en/charactersTab.yaml, src/lib/characterPreview/ShowcaseCustomizationSidebar.tsx, src/types/resources.d.ts
* Added translation support to character preview customization sidebar
*
=> feat: translate character preview customiaztion

src/lib/characterPreview/CharacterPreview.tsx, src/lib/characterPreview/CharacterScoringSummary.tsx, src/lib/characterPreview/ShowcaseCustomizationSidebar.tsx, src/lib/characterPreview/ShowcaseDpsScore.tsx, src/lib/characterPreview/ShowcaseLightCone.tsx, src/lib/tabs/tabShowcase/RelicScorerTab.jsx, src/lib/ui/LoadingBlurredImage.tsx, src/lib/utils/colorUtils.ts, src/style/style.css
* Updating showcase colors
* Tab render optimizations for faster char tab / showcase tab loads
*
=> feat: color palette updates, render optimizations

src/lib/tabs/tabCharacters/CharacterTab.jsx, src/lib/tabs/tabOptimizer/optimizerForm/components/ResultFilters.tsx
* Fixed rating filter header
* Changed "Priority" column in character tab to be 5px wider to accomodate pt-br
*
=> fix: minor layout fixes

src/lib/i18n/i18n.ts, src/lib/tabs/tabRelics/RelicsTab.jsx
* Added japanese to language options on dreary
* Fixed relic grid timeout to properly destroy on language change
*
=> feat: enable japanese

src/lib/characterPreview/CharacterPreview.tsx, src/lib/characterPreview/CharacterScoringSummary.tsx, src/lib/characterPreview/ShowcaseBuildAnalysis.tsx, src/lib/i18n/i18n.ts, src/lib/overlays/drawers/GettingStartedDrawer.tsx, src/lib/overlays/modals/ScoringModal.tsx, src/lib/tabs/Tabs.tsx, src/lib/tabs/tabCharacters/CharacterGrid.tsx, src/lib/tabs/tabCharacters/CharacterTab.jsx, src/lib/utils/colorUtils.ts
* Starting to refactor character tab/grid to ts
* Color changes
*
=> feat: color updates, partial character grid refactor

src/lib/characterPreview/CharacterPreview.tsx, src/lib/characterPreview/CharacterScoringSummary.tsx, src/lib/characterPreview/ShowcaseCustomizationSidebar.tsx, src/lib/scoring/characterScorer.ts, src/lib/simulations/statSimulationController.tsx, src/lib/utils/colorUtils.ts
* Adding diminishing returns on spd substats, capping them at their benchmark's respective max spd sub limit
* Mostly affects kafka builds (buff)
*
=> feat: color updates, diminishing returns on spd scoring

public/locales/en/optimizerTab.yaml
=> fix: unquoted off

src/lib/characterPreview/CharacterPreview.tsx, src/lib/characterPreview/ShowcaseCustomizationSidebar.tsx, src/lib/utils/colorUtils.ts, src/lib/utils/utils.js
* Some more color tweaking for dark mode
*
=> feat: color updates

src/lib/i18n/generateTranslations.ts, src/lib/i18n/i18n.ts
* Added Korean and Vietnamese to language selector options
*
=> feat: add korean and vietnamese to beta

src/lib/relics/relicScorerPotential.ts
* Fixed relicScorer crashing when given only 2 weighted substats that do not include HP/ATK/DEF
* Fixed greedyHash not being properly calculated
*
=> hotfix: relicScorer failing when exactly 2 non-HP/ATK/DEF stats are weighted

public/locales/en/gameData.yaml, public/locales/it/gameData.yaml, src/lib/i18n/LanguageSelector.tsx, src/lib/i18n/betaInformation.ts, src/types/resources.d.ts
* Added names for 2.8 characters, lcs, relics
*
=> feat: 2.8 beta translations

public/locales/de/gameData.yaml, public/locales/en/gameData.yaml, public/locales/es/gameData.yaml, public/locales/fr/gameData.yaml, public/locales/id/gameData.yaml, public/locales/it/gameData.yaml, public/locales/ja/gameData.yaml, public/locales/ko/gameData.yaml, public/locales/pt/gameData.yaml, public/locales/ru/gameData.yaml, public/locales/th/gameData.yaml, public/locales/vi/gameData.yaml, public/locales/zh/gameData.yaml, src/lib/i18n/generateTranslations.ts, src/lib/i18n/i18n.ts, src/types/resources.d.ts
improve gameData generation
* Added Russian to languageSelector options on dreary
* Improved gameData to fallback to english during generation
*
=> feat: enable russian

src/lib/rendering/optionGenerator.ts, src/lib/tabs/tabOptimizer/optimizerForm/components/CharacterSelect.tsx, src/lib/tabs/tabOptimizer/optimizerForm/components/LightConeSelect.tsx, src/lib/tabs/tabRelics/RelicFilterBar.tsx, src/lib/utils/TsUtils.ts, src/lib/worker/optimizerWorker.ts
* Importing DB into TsUtils is invalid since this gets included in the worker, which does not have access to "window"
*
=> refactor: remove DB import from TsUtils

src/lib/interactions/notifications.tsx
* Fixed header for GPU notification not being translated
*
=> fix: translate header for GPU not supported notification

public/locales/en/modals.yaml, src/lib/overlays/modals/RelicModal.tsx, src/types/resources.d.ts
* Fixed relic modal placeholders to support translation
*
=> fix: translate relicModal placeholders

src/lib/conditionals/character/1400/Aglaea.ts, src/lib/conditionals/character/1400/TheHerta.ts, src/lib/conditionals/character/8000/TrailblazerRemembrance.ts, src/lib/conditionals/lightcone/5star/IntotheUnreachableVeil.ts, src/lib/constants/constants.ts, src/lib/state/metadata.ts
=> feat: 3.0v3 content

.github/workflows/starrailoptimizer.yml, public/locales/en/sidebar.yaml, src/lib/constants/constants.ts, src/lib/overlays/drawers/MenuDrawer.tsx
* Update the sidebar for leaks links from starrailoptimizer
* Update menu header to identify no leaks page
*
=> feat: add no leaks link and menu label

docs/guides/en/dps-score.md, docs/guides/en/stat-score.md, src/lib/relics/relicScorerPotential.ts, src/lib/scoring/characterScorer.ts, tests/CharacterPreview/switch-relics-with-character.spec.ts
* DPS score re-scale
* Stat score main stat free roll's all are now 1.0
*
=> feat: scoring balance

public/locales/en_US/charactersTab.yaml, public/locales/en_US/common.yaml, public/locales/en_US/conditionals.yaml, public/locales/en_US/gameData.yaml, public/locales/en_US/getStartedTab.yaml, public/locales/en_US/hint.yaml, public/locales/en_US/hometab.yaml, public/locales/en_US/importSaveTab.yaml, public/locales/en_US/modals.yaml, public/locales/en_US/notifications.yaml, public/locales/en_US/optimizerTab.yaml, public/locales/en_US/relicScorerTab.yaml, public/locales/en_US/relicsTab.yaml, public/locales/en_US/settings.yaml, public/locales/en_US/sidebar.yaml
=> feat: migrate to 4 letter locales

src/lib/characterPreview/ShowcaseLightCone.tsx, src/lib/characterPreview/StatRow.tsx, src/lib/optimization/calculateBuild.ts, src/lib/relics/relicScorerPotential.ts, src/lib/scoring/characterScorer.ts, src/lib/simulations/statSimulationController.tsx, src/lib/utils/colorUtils.ts, src/lib/utils/mathUtils.ts
* Carrying over changes from this PR https://github.com/fribbels/hsr-optimizer/pull/692
* Update poet speed matching to force < 110 spd
* Fix ehr extra max rolls
*
=> feat: dps scoring adjustments, poet spd matching

src/lib/characterPreview/ShowcaseCustomizationSidebar.tsx, src/lib/relics/relicScorerPotential.ts, src/lib/state/metadata.ts, src/lib/utils/colorUtils.ts
* Some color / centering tweaks
* 4 star relics are rated as ? now
*
=> feat: character color/card adjustments, 4 star relics rating '?'

src/lib/conditionals/character/1300/Robin.ts, src/lib/optimization/optimizer.ts, src/lib/overlays/modals/CharacterModal.tsx, src/lib/state/metadata.ts, src/lib/tabs/tabOptimizer/optimizerTabController.ts, src/lib/utils/TsUtils.ts
* Clicking optimizer start will scroll to grid smoother/faster
* Light cone will preselect when selecting a character in the character/team modal
* Shared feeling ohb fix
* Robin ult numbers fix
*
=> feat: faster smooth scrolling to grid, preselect light cone on modal, various fixes

docs/guides/en/troubleshooting.md, public/locales/en/notifications.yaml, public/locales/en_US/notifications.yaml, src/lib/gpu/webgpuOptimizer.ts, src/lib/interactions/notifications.tsx, src/lib/relics/relicScorerPotential.ts, src/lib/tabs/tabShowcase/RelicScorerTab.jsx, src/types/resources.d.ts
* Adding rerun banners for relic scorer presets
* Added gpu acceleration crash docs / placeholder
*
=> feat: relic scorer rerun presets, gpu crash error documetation

public/locales/en_US/conditionals.yaml, src/lib/overlays/modals/BuildsModal.tsx, src/lib/tabs/tabRelics/RelicPreview.tsx, src/lib/ui/ColorizeNumbers.tsx
* Relic shadow was not meant to apply to optimizer
* Removing score label from builds modal 
* Fixing number highlighting logic 
* Black swan skill missing %
*
=> fix: various fixes - remove optimizer relic shadow, builds modal score, carve lc number highlighting

public/locales/en_US/charactersTab.yaml, src/lib/characterPreview/CharacterPreview.tsx, src/lib/characterPreview/CharacterPreviewComponents.tsx, src/lib/characterPreview/CharacterStatSummary.tsx, src/lib/characterPreview/ShowcaseBuildAnalysis.tsx, src/lib/characterPreview/ShowcaseCharacterHeader.tsx, src/lib/characterPreview/ShowcaseLightCone.tsx, src/lib/characterPreview/ShowcaseRelicsPanel.tsx, src/lib/constants/constants.ts, src/lib/tabs/tabRelics/RelicPreview.tsx, src/lib/utils/colorUtils.ts, src/lib/utils/utils.js, src/style/style.css, src/types/resources.d.ts
* Adding unscored card layout for weird characters like serval
* Fix i18n resolved language crash on screenshot
*
=> feat: unscored showcase card layout

src/lib/characterPreview/ShowcaseCustomizationSidebar.tsx, src/lib/state/metadata.ts
* `+ poet + eagle - genius` for general relic matching
* `- glamoth` for general ornament matching
* Various other defaults changing
*
=> feat: metadata default set changes

src/lib/characterPreview/CharacterPreviewComponents.tsx, src/lib/characterPreview/ShowcaseStatScore.tsx
* Discovered a bug with shadows on mobile
*
=> feat: fix shadow on mobile or safari browsers, fix font weight

src/lib/conditionals/character/1400/Aglaea.ts
* Seam stitch was missing and additional dmg was tied to ult instead, fixing to its own conditional
*
=> fix: aglaea seam stitch conditional missing

public/locales/en_US/conditionals.yaml, public/locales/en_US/optimizerTab.yaml
=> feat: 3.0 conditionals

src/lib/relics/relicScorerPotential.ts, src/lib/state/metadata.ts, tests/CharacterPreview/switch-relics-with-character.spec.ts
* Changed the relic potential algorithm to match main stat if it is an optimal main stat
* Changed the relic potential algorithm to consistently choose the same mainstat for the optimal part
*
=> feat: relic potential updates

src/lib/characterPreview/CharacterPreview.tsx, src/lib/characterPreview/CharacterPreviewComponents.tsx, src/lib/characterPreview/ShowcaseCustomizationSidebar.tsx, src/lib/characterPreview/characterPreviewController.tsx, src/lib/utils/colorUtils.ts
* Updating color picker to avoid orange colors
* Portrait -> LC gap narrowed to 8
* Shadow narrowed to 4
* Fixed some orange/yellow portrait colors
*
=> feat: update auto color picking algorithm

src/lib/characterPreview/CharacterScoringSummary.tsx, src/lib/characterPreview/CharacterStatSummary.tsx, src/lib/characterPreview/ShowcaseCustomizationSidebar.tsx
* Removing CV row from card
* Added a scoring disclaimer
* Adjusted logic for showing OHB/ERR
* Some more color tweaking
*
=> feat: remove CV, scoring analysis tweaks + disclaimer

src/lib/characterPreview/CharacterScoringSummary.tsx, src/lib/characterPreview/CharacterStatSummary.tsx, src/lib/characterPreview/ShowcaseCustomizationSidebar.tsx, src/lib/characterPreview/StatRow.tsx, src/lib/constants/constantsSession.ts, src/lib/overlays/drawers/StatTracesDrawer.tsx, src/lib/state/db.ts, src/style/style.css, src/types/store.d.ts
* Select .0 or .000 spd precision
*
=> feat: spd precision showcase selector

public/locales/en_US/hometab.yaml, src/lib/characterPreview/CharacterPreview.tsx, src/lib/characterPreview/CharacterPreviewComponents.tsx, src/lib/characterPreview/ShowcaseCustomizationSidebar.tsx, src/lib/tabs/tabHome/HomeTab.tsx, src/lib/ui/ColorizedLink.tsx, src/lib/utils/colorUtils.ts, src/types/resources.d.ts
* Adding enka attribution to home page
* https://github.com/fribbels/hsr-optimizer/issues/849
=> feat: api attribution

public/locales/en_US/conditionals.yaml, src/lib/conditionals/character/1100/Seele.ts, src/types/resources.d.ts
* Fixed inconsistencies in the conditional content text formatting
*
=> fix: conditional text formatting

src/lib/characterPreview/CharacterPreviewComponents.tsx, src/lib/utils/utils.js
* Testing zoom instead of pixel scale to generate showcase images
*
=> feat: fix showcase shadows on mobile or safari

src/lib/characterPreview/CharacterPreviewComponents.tsx, src/lib/characterPreview/ShowcaseCustomizationSidebar.tsx, src/lib/utils/utils.js
* Fixing shadow rendering on safari/mobile
* ~~Adjusting mobile to use clipboard~~
*
=> fix: clean up y axis shadow on mobile/safari

public/locales/en_US/charactersTab.yaml, public/locales/en_US/optimizerTab.yaml, src/lib/characterPreview/CharacterScoringSummary.tsx, src/lib/overlays/drawers/StatTracesDrawer.tsx, src/lib/tabs/tabOptimizer/optimizerForm/components/AdvancedOptionsPanel.tsx, src/lib/tabs/tabRelics/RelicsTab.jsx, src/types/metadata.d.ts, src/types/resources.d.ts
* Added translation for the custom stat traces drawer
* Fixed relic locator settings overflow in `fr-FR`/`pt-BR`
* Added translation for Scoring Note at top of build analysis
*
=> fix: translation tweaks

public/locales/en_US/conditionals.yaml, src/lib/conditionals/character/1000/Asta.ts, src/lib/conditionals/character/1000/SilverWolf.ts, src/lib/conditionals/lightcone/4star/ResolutionShinesAsPearlsOfSweat.ts, src/lib/conditionals/lightcone/5star/InherentlyUnjustDestiny.ts, src/types/resources.d.ts
* Changed conditionals to include base chance where left unspecified
* Fixed conditionals using a static scaling where it should be dynamic
*
=> fix: conditionals values not dynamic

src/lib/characterPreview/CharacterScoringSummary.tsx
* Fixed text not aligned to center
*
=> fix: align text to center

public/locales/en_US/conditionals.yaml, src/types/resources.d.ts
=> fix: Seele speed boost conditional typo

public/locales/en_US/charactersTab.yaml, src/lib/characterPreview/CharacterPreviewComponents.tsx, src/lib/characterPreview/CharacterScoringSummary.tsx, src/lib/characterPreview/ShowcaseCustomizationSidebar.tsx, src/lib/characterPreview/ShowcaseDpsScore.tsx, src/lib/scoring/characterScorer.ts, src/lib/scoring/simScoringUtils.ts, src/lib/tabs/tabOptimizer/optimizerForm/components/RecommendedPresetsButton.tsx, src/types/resources.d.ts
=> feat: updating stat customization sidebar display

public/locales/en_US/charactersTab.yaml, src/lib/characterPreview/ShowcaseCustomizationSidebar.tsx, src/types/resources.d.ts
* Added translation support for scoring section of characters tab sidebar
*
=> feat: translate scoring sidebar in character tab

src/lib/conditionals/character/1400/Mydei.ts, src/lib/conditionals/character/1400/Tribbie.ts, src/lib/conditionals/lightcone/5star/IfTimeWereAFlower.ts, src/lib/constants/constants.ts, src/lib/gpu/conditionals/setConditionals.ts, src/lib/gpu/injection/injectConditionals.ts, src/lib/gpu/wgsl/computeShader.wgsl, src/lib/optimization/calculateBuild.ts, src/lib/optimization/calculateStats.ts, src/lib/state/metadata.ts, src/lib/worker/optimizerWorker.ts, src/types/conditionals.d.ts
=> feat: 3.1v3 updates

public/locales/en_US/charactersTab.yaml
=> fix: spd precision label

src/lib/characterPreview/CharacterPreview.tsx, src/lib/characterPreview/ShowcaseCustomizationSidebar.tsx, src/lib/characterPreview/ShowcasePortrait.tsx, src/lib/constants/constantsSession.ts, src/lib/state/db.ts, src/types/store.d.ts
- Fixed eslint no displayname error for customization sidebar
- Fixed some lines that should have been formatted in the first place
- Added show/hide uid buttons
- Added showcaseUID to state management
- Added uid shows/hides on character portrait
* Closes #771 
Already DM'd fribbels
=> feat: add show/hide uid option on showcase

public/locales/en_US/charactersTab.yaml, src/lib/characterPreview/ShowcaseCustomizationSidebar.tsx, src/types/resources.d.ts
* Added translation for Show UID toggle in customization sidebar
*
=> feat: add translation for showcase UID toggle

src/lib/characterPreview/CharacterPreview.tsx, src/lib/characterPreview/CharacterPreviewComponents.tsx, src/lib/characterPreview/ShowcaseCustomizationSidebar.tsx, src/lib/characterPreview/ShowcaseLightCone.tsx, src/lib/characterPreview/ShowcasePortrait.tsx, src/lib/tabs/tabHome/HomeTab.tsx, src/lib/tabs/tabOptimizer/Sidebar.tsx, src/lib/tabs/tabOptimizer/optimizerForm/grid/OptimizerGrid.jsx, src/lib/tabs/tabRelics/RelicPreview.tsx, src/lib/tabs/tabRelics/RelicsTab.jsx, src/lib/tabs/tabWarp/WarpCalculatorTab.tsx, src/lib/utils/colorUtils.ts, src/style/style.css, tests/RelicModal/3-edit-from-relics-tab.spec.ts
* Adding UID label
* Fix some warp tab labels
* Adding inset card border
* Hide UID on characters tab
* Prevent user highlight radios
* Warp guarantees to icons
* Fix Learn More button height
*
=> feat: various ui tweaks 

src/lib/characterPreview/ShowcaseDpsScore.tsx, src/lib/conditionals/evaluation/dependencyEvaluator.ts, src/lib/gpu/webgpuOptimizer.ts, src/lib/relics/relicScorerPotential.ts, src/lib/scoring/characterScorer.ts, src/lib/state/db.ts, src/lib/utils/colorUtils.ts
* Scores to ? when not full builds
* Color tweaks
* Cleaning up spammy logs
*
=> feat: setting scores to ? for non - 6 piece builds

public/locales/en_US/importSaveTab.yaml, src/lib/tabs/tabImport/ScannerImportSubmenu.tsx, src/types/resources.d.ts
* Added a checkbox to only import existing characters
* Closes #919
=> feat: add checkbox to only import existing characters

src/lib/i18n/i18n.ts
* Removed i18n::backendConnector logs
* Closes #924
=> fix: disable i18n::backendConnector logs

src/lib/simulations/statSimulationController.tsx, src/lib/tabs/tabOptimizer/optimizerForm/components/SimulatedBuildsGrid.tsx, src/lib/tabs/tabOptimizer/optimizerForm/components/StatSimulationDisplay.tsx, src/types/store.d.ts
* Added an "overwrite build" button to the custom stat simulator
* Closes #925
=> feat: stat sim swap button

src/lib/characterPreview/ShowcaseDpsScore.tsx, src/lib/scoring/characterScorer.ts, src/lib/tabs/tabHome/HomeTab.tsx
* Home page searches on enter now
* No light cone = ? dps score
*
=> feat: home page enter button search, missing light cone scoring (?)

src/lib/characterPreview/CharacterPreview.tsx, src/lib/characterPreview/CharacterScoringSummary.tsx, src/lib/gpu/webgpuOptimizer.ts, src/lib/optimization/bufferPacker.ts, src/lib/optimization/calculateBuild.ts, src/lib/optimization/optimizer.ts, src/lib/simulations/combatBuffsAnalysis.ts, src/lib/simulations/statSimulationController.tsx, src/lib/worker/optimizerWorker.ts, src/lib/worker/workerPool.ts
* Some width fixes to the showcase
* Started a WIP combat buffs display, pushing the tooling first while working on the UI
*
=> feat: combat buffs wip

index.html, src/lib/characterPreview/CharacterScoringSummary.tsx, src/lib/i18n/LanguageSelector.tsx, src/lib/tabs/tabCharacters/CharacterTab.jsx, src/lib/ui/ColorizeNumbers.tsx
* Changed `ColorizeNumbers.tsx` to not modify strings when inContext language is selected
*
=> fix: enable inContext conditionals content translation

package-lock.json, package.json, src/lib/constants/constants.ts, src/lib/tabs/tabWarp/WarpCalculatorTab.tsx, src/lib/tabs/tabWarp/warpCalculatorController.test.ts, src/lib/tabs/tabWarp/warpCalculatorController.ts
* Basic warp calculator tests to maintain consistency
*
=> tests: basic warp calculator tests

public/locales/en_US/conditionals.yaml, src/lib/conditionals/character/1000/Arlan.ts, src/lib/conditionals/character/1000/Asta.ts, src/lib/conditionals/character/1000/DanHeng.ts, src/lib/conditionals/character/1000/Herta.ts, src/lib/conditionals/character/1000/Himeko.ts, src/lib/conditionals/character/1000/Kafka.ts, src/lib/conditionals/character/1000/March7th.ts, src/lib/conditionals/character/1000/SilverWolf.ts, src/lib/conditionals/character/1000/Welt.ts, src/lib/conditionals/character/1100/Clara.ts, src/lib/conditionals/character/1100/Gepard.ts, src/lib/conditionals/character/1100/Hook.ts, src/lib/conditionals/character/1100/Luka.ts, src/lib/conditionals/character/1100/Lynx.ts, src/lib/conditionals/character/1100/Natasha.ts, src/lib/conditionals/character/1100/Pela.ts, src/lib/conditionals/character/1100/Sampo.ts, src/lib/conditionals/character/1100/Seele.ts, src/lib/conditionals/character/1100/Serval.ts, src/lib/conditionals/character/1100/Topaz.ts, src/types/resources.d.ts
* 10xx characters buffs
* 11xx characters buffs
* Fixed a few additional dmg procs
*
=> feat: buff tracing 10xx 11xx conditionals

src/lib/conditionals/character/1000/Herta.ts, src/lib/conditionals/character/1000/Welt.ts, src/lib/conditionals/character/1100/Hook.ts, src/lib/conditionals/character/1100/Serval.ts, src/lib/conditionals/character/1200/March7thImaginary.ts, src/lib/conditionals/character/1200/Moze.ts, src/lib/conditionals/character/1200/Sushang.ts, src/lib/conditionals/character/1200/Tingyun.ts, src/lib/conditionals/character/1200/Yanqing.ts, src/lib/conditionals/character/1300/DrRatio.ts, src/lib/conditionals/character/1300/Jade.ts, src/lib/conditionals/conditionalFinalizers.ts, src/lib/conditionals/lightcone/3star/HiddenShadow.ts, src/lib/conditionals/lightcone/4star/WeWillMeetAgain.ts
* Previously additional dmg was added to base scaling, so it would get ability based buffs when it shouldnt. Updated all additional dmg conditionals
*
=> feat: additional dmg conditional updates

src/lib/characterPreview/BuffsAnalysisDisplay.tsx, src/lib/characterPreview/CharacterScoringSummary.tsx, src/lib/optimization/basicStatsArray.ts, src/lib/optimization/buffSource.ts, src/lib/optimization/calculateBuffs.ts, src/lib/optimization/computedStatsArray.ts, src/lib/simulations/combatBuffsAnalysis.ts, src/lib/simulations/expandedComputedStats.ts
* Changed the string buff sources to BuffSource objects
* Slowly improving the UI
*
=> feat: update buff tracking to objects, temporary ui display

src/lib/conditionals/character/1400/Mydei.ts, src/lib/conditionals/character/1400/Tribbie.ts, src/lib/constants/constants.ts, src/lib/state/metadata.ts
* Mydei/Tribbie v5 changes
* Tribbie SPD weight 0 -> 1, defaults to genius set. Enabled matching for poet + longevous
*
=> feat: 3.1v5 content

src/lib/tabs/tabWarp/WarpCalculatorTab.tsx, src/lib/tabs/tabWarp/warpCalculatorController.ts
* Removing checkboxes in favor of selectable leaf nodes
* Fixed a crash on null form values
* Widen the form a bit
*
=> feat: warp tab ui tweaks

index.html, src/lib/characterPreview/BuffsAnalysisDisplay.tsx, src/lib/characterPreview/ShowcaseCustomizationSidebar.tsx, src/lib/scoring/characterScorer.ts, src/lib/tabs/tabOptimizer/optimizerForm/optimizerFormTransform.ts, src/lib/tabs/tabWarp/WarpCalculatorTab.tsx, src/lib/utils/colorUtils.ts
* Update index.html
* Don't suggest rope upgrade on forced err rope
* Fix optimizer form not saving changes
* Various color updates
* Single column buff display option
* Fixing crashes on save loads for warp tab
*
=> feat: index.html updates, various fixes

public/locales/en_US/optimizerTab.yaml, src/lib/characterPreview/CharacterScoringSummary.tsx, src/lib/i18n/i18n.ts, src/lib/overlays/modals/EditImageModal.tsx, src/lib/tabs/tabOptimizer/optimizerForm/components/ComboFilter.tsx, src/lib/tabs/tabRelics/RelicsTab.jsx, src/lib/tabs/tabRelics/relicPreview/RelicStatText.tsx, src/types/resources.d.ts
* Added `vn-VI` to available languages on main page
* minor styling tweaks
* Added missing translation
* This is in anticipation of crowdin updates that are not yet merged
=> feat: enable vietnamese

src/lib/tabs/tabOptimizer/optimizerForm/components/RelicMainSetFilters.tsx
* Relic set filters were broken, re-enabling
*
=> fix: relic set filters

src/lib/optimization/optimizer.ts, src/lib/tabs/tabOptimizer/OptimizerBuildPreview.tsx, src/lib/tabs/tabOptimizer/analysis/DamageSplits.tsx, src/lib/tabs/tabOptimizer/analysis/ExpandedDataPanel.tsx, src/lib/tabs/tabOptimizer/analysis/SubstatUpgrades.tsx, src/lib/tabs/tabOptimizer/analysis/expandedDataPanelController.ts, src/lib/tabs/tabOptimizer/combo/comboDrawerController.tsx, src/lib/tabs/tabOptimizer/optimizerForm/optimizerFormTransform.ts, src/lib/tabs/tabOptimizer/optimizerTabController.ts, src/lib/worker/workerPool.ts
* Update form handling to select & show the top row on character changes
* Don't render expensive optimizer components unless tab is optimizer
* Fix combo state generation crashes
*
=> feat: update optimizer form handling logic for expanded panel

src/lib/characterPreview/BuffsAnalysisDisplay.tsx, src/lib/characterPreview/CharacterPreview.tsx, src/lib/characterPreview/CharacterScoringSummary.tsx, src/lib/characterPreview/ShowcaseCustomizationSidebar.tsx, src/lib/characterPreview/ShowcaseDpsScore.tsx, src/lib/characterPreview/StatRow.tsx, src/lib/scoring/simScoringUtils.ts, src/lib/simulations/combatBuffsAnalysis.ts, src/lib/state/db.ts, src/lib/tabs/tabOptimizer/analysis/ExpandedDataPanel.tsx, src/lib/tabs/tabOptimizer/optimizerForm/grid/OptimizerGrid.jsx, src/lib/tabs/tabRelics/RelicsTab.jsx, src/lib/utils/arrayUtils.ts, src/lib/utils/debounceUtils.ts
* Optimizer analysis memo'd
* Some performance cleanup
* Fix builds modal weirdness
* Adding debounceUtils and debouncing relics tab refresh
*
=> feat: various rendering optimizations, bug fixes

public/locales/en_US/optimizerTab.yaml, src/lib/state/db.ts, src/lib/tabs/tabOptimizer/OptimizerBuildPreview.tsx, src/lib/tabs/tabOptimizer/analysis/DamageSplits.tsx, src/lib/tabs/tabOptimizer/analysis/DamageSplitsChart.tsx, src/lib/tabs/tabOptimizer/analysis/ExpandedDataPanel.tsx, src/lib/tabs/tabOptimizer/analysis/StatsDiffCard.tsx, src/lib/tabs/tabOptimizer/analysis/SubstatUpgrades.tsx, src/lib/tabs/tabOptimizer/optimizerForm/grid/OptimizerGrid.jsx, src/lib/tabs/tabOptimizer/optimizerForm/layout/FilterContainer.tsx, src/lib/tabs/tabOptimizer/optimizerForm/layout/FormCard.tsx, src/lib/tabs/tabOptimizer/optimizerForm/layout/FormRow.tsx, src/style/style.css, src/types/resources.d.ts
* Making analysis panel collapsable
* Remove responsive chart wrapper
*
=> feat: moving optimization results analysis to a FormRow, standardize the borders / layout

src/lib/tabs/tabWarp/WarpCalculatorTab.tsx, src/style/style.css
* Separating the halves labels with a space for readability
*
=> feat: add divider between additional resources groups

src/lib/characterPreview/ShowcasePortrait.tsx, src/lib/state/metadata.ts, src/lib/tabs/tabChangelog/ChangelogTab.tsx, src/lib/tabs/tabOptimizer/optimizerForm/components/TeammateCard.tsx
* Switch UID / artist positions
* Blade defaults to Bone
* Update presets
* -Bronya -Sparkle for sacerdos x2
*
=> feat: metadata updates

src/lib/tabs/tabOptimizer/Sidebar.tsx, src/lib/tabs/tabOptimizer/analysis/expandedDataPanelController.ts, src/lib/tabs/tabOptimizer/optimizerTabController.ts
* Noticed a crash on beta on .getGridOption but couldnt replicate it on local, adding in some ? checks just in case
*
=> fix: gridoptions crash on beta

public/locales/en_US/charactersTab.yaml, public/locales/en_US/importSaveTab.yaml, public/locales/tr_TR/gameData.yaml, src/lib/characterPreview/CharacterScoringSummary.tsx, src/lib/utils/i18nUtils.ts, src/types/resources.d.ts
* Added support for Turkish translation
*
=> feat: turkish translation support

public/locales/en_US/notifications.yaml, src/lib/overlays/modals/CharacterModal.tsx, src/lib/tabs/tabOptimizer/combo/ComboDrawer.tsx
* Combo drawer was bugging out on rendering number sliders
* GPU error msg to suggest updating browser
* Trailblazers should default to e6
*
=> feat: combo drawer rendering fix, gpu error msg update, trailblazer selector default to e6

public/locales/en_US/importSaveTab.yaml, src/lib/importer/characterConverter.ts, src/lib/importer/hoyoLabFormatParser.tsx, src/lib/importer/kelzFormatParser.tsx, src/lib/interactions/message.ts, src/lib/relics/relicAugmenter.ts, src/lib/relics/relicRollFixer.ts, src/lib/relics/relicRollGrader.ts, src/lib/state/db.ts, src/lib/tabs/tabImport/ScannerImportSubmenu.tsx, src/types/relic.d.ts, src/types/resources.d.ts
* Added count and step importing to reliquary and enka import methods
* Added translation for kelz import errors
*
=> feat: import roll counts and steps

public/locales/en_US/conditionals.yaml, public/locales/en_US/optimizerTab.yaml, src/lib/conditionals/character/1300/Acheron.ts, src/lib/conditionals/character/1300/Sparkle.ts, src/lib/conditionals/character/1400/TheHerta.ts, src/lib/conditionals/conditionalUtils.ts, src/lib/conditionals/lightcone/4star/PoisedToBloom.ts, src/lib/constants/constants.ts, src/lib/gpu/injection/injectConditionals.ts, src/lib/gpu/wgsl/computeShader.wgsl, src/lib/gpu/wgsl/structs.wgsl, src/lib/optimization/config/setsConfig.ts, src/lib/optimization/rotation/comboStateTransform.ts, src/lib/tabs/tabOptimizer/optimizerForm/components/FormSetConditionals.jsx, src/types/optimizer.d.ts, src/types/resources.d.ts
* Added precompute for team composition specific effects
* Fixed penacony not applying to memosprites
* Closes #498
=> feat: precompute element/path conditionals

public/locales/en_US/charactersTab.yaml, src/lib/characterPreview/CharacterScoringSummary.tsx, src/lib/characterPreview/summary/DpsScoreGradeRuler.tsx, src/lib/overlays/modals/RelicModal.tsx, src/lib/scoring/characterScorer.ts, src/lib/scoring/simScoringUtils.ts, src/lib/tabs/tabOptimizer/analysis/DamageSplitsChart.tsx
* Adding ruler chart
* Rearrange dps score analysis
*
=> feat: adding dps score progress bar

docs/guides/en/dps-score.md, src/lib/characterPreview/BuffsAnalysisDisplay.tsx, src/lib/tabs/tabOptimizer/analysis/SubstatUpgrades.tsx, src/lib/tabs/tabOptimizer/analysis/expandedDataPanelController.ts, src/style/style.css
* Use consistent table styling for buff upgrades
* Change roll values to max roll for upgrades
*
=> feat: update buff table styling, change substat upgrades to max roll value

public/locales/en_US/conditionals.yaml, src/lib/conditionals/lightcone/4star/PlanetaryRendezvous.ts, src/lib/conditionals/lightcone/4star/TodayIsAnotherPeacefulDay.ts, src/lib/conditionals/resolver/lightConeConditionalsResolver.ts, src/lib/gpu/injection/injectConditionals.ts, src/lib/optimization/context/calculateContext.ts, src/lib/optimization/rotation/comboStateTransform.ts, src/lib/scoring/characterScorer.ts, src/lib/state/db.ts, src/lib/tabs/tabOptimizer/combo/comboDrawerController.tsx, src/lib/tabs/tabOptimizer/conditionals/LightConeConditionalDisplay.tsx, src/lib/tabs/tabOptimizer/optimizerForm/OptimizerForm.tsx, src/lib/tabs/tabOptimizer/optimizerForm/components/TeammateCard.tsx, src/lib/tabs/tabOptimizer/optimizerForm/optimizerFormTransform.ts, src/types/form.d.ts, src/types/metadata.d.ts, src/types/optimizer.d.ts, src/types/resources.d.ts, src/types/window.d.ts
* Added path matching check to light cone conditionals
* Added wearer information to better process lc conditionals (planetary, peaceful day)
* Changed context and comboCharacter metadata accordingly
*
=> feat: disable lc conditionals on path mismatch

src/lib/characterPreview/CharacterScoringSummary.tsx, src/lib/characterPreview/summary/DpsScoreGradeRuler.tsx, src/lib/tabs/tabWarp/warpCalculatorController.test.ts, src/lib/tabs/tabWarp/warpCalculatorController.ts
* Disable 3.0 income, add 3.2
* Change mobile dps score disclaimer text
*
=> feat: 3.2 income, dps score disclaimer styling for mobile

src/lib/characterPreview/BuffsAnalysisDisplay.tsx, src/lib/characterPreview/CharacterPreview.tsx, src/lib/characterPreview/CharacterStatSummary.tsx, src/lib/characterPreview/ShowcasePortrait.tsx, src/lib/characterPreview/characterPreviewController.tsx, src/lib/conditionals/character/1400/TheHerta.ts, src/lib/conditionals/resolver/lightConeConditionalsResolver.ts, src/lib/gpu/tests/webgpuTestUtils.ts, src/lib/gpu/webgpuOptimizer.ts, src/lib/optimization/config/computedStatsConfig.ts, src/lib/scoring/characterScorer.ts, src/lib/tabs/tabWebgpu/WebgpuTab.tsx
* Fix stat config labels
* Fix herta scaling
* Fix light cone / portrait pixel offsets
* Reenabled GPU tests to use all lc effects
*
=> feat: stat config labels

src/lib/conditionals/character/1100/Bronya.ts, src/lib/conditionals/character/1100/Gepard.ts, src/lib/conditionals/character/1100/Lynx.ts, src/lib/conditionals/character/1200/FuXuan.ts, src/lib/conditionals/character/1200/Hanya.ts, src/lib/conditionals/character/1200/Jiaoqiu.ts, src/lib/conditionals/character/1200/Tingyun.ts, src/lib/conditionals/character/1300/Aventurine.ts, src/lib/conditionals/character/1300/Firefly.ts, src/lib/conditionals/character/1300/Gallagher.ts, src/lib/conditionals/character/1300/Robin.ts, src/lib/conditionals/character/1300/Sparkle.ts, src/lib/conditionals/character/1300/Sunday.ts, src/lib/conditionals/character/1400/Mydei.ts, src/lib/conditionals/character/8000/TrailblazerHarmony.ts, src/lib/conditionals/character/8000/TrailblazerRemembrance.ts, src/lib/conditionals/evaluation/statConversion.ts, src/lib/conditionals/lightcone/4star/PerfectTiming.ts
* Added buff source tracing to `dynamicStatConversion()`
*
=> feat: track dynamicStatConversion() buffs

src/lib/conditionals/character/1200/Hanya.ts, src/lib/conditionals/character/1300/Sunday.ts, src/lib/optimization/defaultForm.ts, src/lib/overlays/drawers/MenuDrawer.tsx, src/lib/state/metadata.ts, src/lib/tabs/tabOptimizer/analysis/StatsDiffCard.tsx, src/lib/tabs/tabOptimizer/optimizerForm/components/RecommendedPresetsButton.tsx, src/style/style.css
* Prevent menu text highlight
* Sunday E6 to unconvertible
* Remove Mydei ATK% sim
* Disable hero set by default
* Update Hanya SPD cap to 300
* Fix stat arrow on mac
* Add glamoth to anaxa matching sims
*
=> fix: various fixes

src/lib/optimization/defaultForm.ts, src/lib/tabs/tabOptimizer/optimizerForm/components/RecommendedPresetsButton.tsx
* Fixes characterPreview and speed preset button crashing
*
=> fix: speed preset and character preview crashing

src/lib/conditionals/character/1400/Castorice.ts, src/lib/optimization/rotation/rotationPreprocessor.ts, src/lib/tabs/tabOptimizer/combo/comboDrawerController.tsx, src/lib/tabs/tabOptimizer/conditionals/FormSlider.tsx
* Castorice v4 combo rotation update
*
=> hotfix: advanced combo & preprocessor updates

src/lib/characterPreview/CharacterPreview.tsx, src/lib/characterPreview/CharacterPreviewComponents.tsx, src/lib/characterPreview/summary/DpsScoreMainStatUpgradesTable.tsx, src/lib/characterPreview/summary/StatScoringSummary.tsx, src/lib/scoring/characterScorer.ts, src/lib/utils/colorUtils.ts, src/lib/worker/baseOptimizerWorker.ts, src/lib/worker/workerPool.ts
* Fixed a bug with poet sim exceeding spd
* Stat score styling
* Separate optimizer worker from other workers 
* Fix -0.1 score diffs
*
=> feat: various showcase improvements

src/lib/tabs/tabOptimizer/combo/ComboDrawer.tsx, src/style/style.css
* Sort combo values
* Add dividers between partitions
*
=> feat: advanced combo improvements

src/lib/characterPreview/ShowcaseBuildAnalysis.tsx, src/lib/characterPreview/summary/StatScoringSummary.tsx, src/lib/characterPreview/summary/statScoringSummaryController.ts, src/lib/constants/constants.ts
* Adding announcement banner for beta versions
*
=> feat: adding beta character info messaging banner

src/lib/characterPreview/CharacterPreview.tsx, src/lib/characterPreview/ShowcaseBuildAnalysis.tsx, src/lib/conditionals/character/1400/Anaxa.ts, src/lib/conditionals/character/1400/Castorice.ts, src/lib/conditionals/lightcone/5star/LifeShouldBeCastToFlames.ts, src/lib/constants/constants.ts, src/lib/interactions/CharacterAnnouncement.tsx, src/lib/state/metadata.ts
* Adding character announcement banner to main
* Prep for 3.2v5
*
=> feat: add character announcement banner, 3.2v5

src/lib/characterPreview/CharacterPreviewComponents.tsx, src/lib/characterPreview/ShowcaseDpsScore.tsx, src/lib/characterPreview/ShowcaseLightCone.tsx, src/lib/characterPreview/summary/StatScoringSummary.tsx, src/lib/tabs/tabRelics/RelicPreview.tsx, src/lib/tabs/tabShowcase/RelicScorerTab.jsx
* Perfection gradient using quality colors
* Fixing safari outline/border bug
* Relic scorer edit/simulate on another character defaults to the selected character now
*
=> feat: visual improvements - safari border fix, perfection bar gradient, fill in default character on edit button

src/lib/conditionals/character/1300/Robin.ts, src/lib/relics/relicRollGrader.ts, src/lib/rendering/renderer.tsx, src/lib/state/metadata.ts, src/lib/worker/estTbpWorkerRunner.ts
* Change robin default atk to 4500
* Relic roll grader fixes
* Fixes for dark reader grade colors
*
=> feat: various fixes, robin defaults to 4500 atk, relic grader failures, dark reader colors

src/lib/characterPreview/summary/StatScoringSummary.tsx, src/lib/conditionals/resolver/characterConditionalsResolver.ts, src/lib/state/db.ts, src/lib/tabs/tabOptimizer/conditionals/CharacterConditionalsDisplay.tsx, src/lib/worker/optimizerWorker.ts
=> refactor: testing if dynamically load conditional files work in beta

src/lib/conditionals/character/1400/Anaxa.ts, src/lib/constants/constants.ts
=> feat: 3.2v6

public/locales/en_US/charactersTab.yaml, public/locales/en_US/common.yaml, public/locales/en_US/getStartedTab.yaml, public/locales/en_US/warpCalculatorTab.yaml, src/lib/characterPreview/BuffsAnalysisDisplay.tsx, src/lib/characterPreview/summary/DpsScoreGradeRuler.tsx, src/lib/characterPreview/summary/DpsScoreSubstatUpgradesTable.tsx, src/lib/characterPreview/summary/StatScoringSummary.tsx, src/lib/constants/constants.ts, src/lib/interactions/CharacterAnnouncement.tsx, src/lib/overlays/drawers/GettingStartedDrawer.tsx, src/lib/tabs/tabOptimizer/optimizerForm/components/RecommendedPresetsButton.tsx, src/lib/tabs/tabWarp/WarpCalculatorTab.tsx, src/style/style.css, src/types/resources.d.ts
* ~~[ ] Added translation for buff labels~~ to be handled in seperate PR
*
=> feat: translation updates

public/locales/en_US/charactersTab.yaml, src/lib/characterPreview/CharacterScoringSummary.tsx, src/lib/characterPreview/ShowcaseBuildAnalysis.tsx, src/lib/characterPreview/summary/EstimatedTbpRelicsDisplay.tsx, src/lib/characterPreview/summary/statScoringSummaryController.ts, src/lib/interactions/CharacterAnnouncement.tsx, src/lib/rendering/theme.ts
* Adding est tbp to the combat score with a disclaimer
*
=> feat: adding stat score analysis to dps score

src/lib/characterPreview/ShowcaseCustomizationSidebar.tsx, src/lib/conditionals/character/1200/Jiaoqiu.ts, src/lib/overlays/modals/RelicModal.tsx, src/lib/overlays/modals/relicModalController.ts, src/lib/tabs/tabOptimizer/optimizerTabController.ts, src/lib/tabs/tabRelics/RelicsTab.jsx
=> feat: show spd decimals on relic modal upgrades, missing teammate optimization warning, various bug fixes

public/locales/en_US/conditionals.yaml, src/lib/conditionals/character/1400/Anaxa.ts, src/lib/conditionals/character/1400/Castorice.ts, src/lib/conditionals/lightcone/4star/TheGreatCosmicEnterprise.ts, src/lib/conditionals/lightcone/5star/LifeShouldBeCastToFlames.ts, src/lib/conditionals/lightcone/5star/MakeFarewellsMoreBeautiful.ts, src/types/resources.d.ts
* Added descriptions for 3.2 conditionals
*
=> feat: 3.2 conditionals descriptions

src/lib/utils/utils.js
* Fixed: uncaught type error when saving build screenshot?
* https://github.com/bubkoo/html-to-image/issues/508
=> fix: uncaught type error when saving screenshot

public/locales/en_US/common.yaml, public/locales/en_US/relicsTab.yaml, src/icons/CircleIcon.tsx, src/icons/RingedCircle4Icon.tsx, src/icons/RingedCircleCheckIcon.tsx, src/icons/RingedCircleIcon.tsx, src/lib/relics/relicRollFixer.ts, src/lib/relics/relicRollGrader.ts, src/lib/rendering/renderer.tsx, src/lib/state/db.ts, src/lib/tabs/tabRelics/RelicFilterBar.tsx, src/lib/tabs/tabRelics/RelicsTab.jsx, src/types/relic.d.ts, src/types/resources.d.ts, src/types/store.d.ts
* Added filter for 4/3 liners
* non 5 star relics are considered to be 0 liners
*
=> feat: filter 4 liners

public/locales/en_US/optimizerTab.yaml, src/icons/RingedCircle4Icon.tsx, src/icons/RingedCircleCheckIcon.tsx, src/icons/RingedCircleIcon.tsx, src/icons/UpArrow.tsx, src/lib/state/db.ts, src/lib/tabs/tabOptimizer/optimizerForm/components/OptimizerOptionsDisplay.tsx
* Few bug fixes before the patch
* +0 main stat option
* Replacing some antd icons with just the svg
* Removing dead #getting-started tab
*
=> feat: main stat boost +0, fix icons and #getting-started tab

src/lib/relics/relicRollGrader.ts, src/lib/relics/statCalculator.ts
* Fixed over-precise roll validation
*
=> fix: bad roll validation

public/locales/en_US/charactersTab.yaml, src/lib/characterPreview/ShowcaseDpsScore.tsx, src/lib/tabs/tabImport/ScannerImportSubmenu.tsx, src/types/resources.d.ts
* Added seperate warning message for no lc
* Disabled existing characters only import toggle when no characters
*
=> feat: no lc warning message, disabling import toggle on no characters

src/lib/tabs/tabOptimizer/combo/comboDrawerController.tsx
* Fixing an issue with combo state, from an unfinished todo
* Bug report: https://discord.com/channels/800607517074784256/1189053007741067294/1360687593859322037
*
=> fix: advanced combo duplicting base conditional

public/locales/en_US/optimizerTab.yaml, public/locales/en_US/relicScorerTab.yaml, public/locales/en_US/settings.yaml, src/lib/characterPreview/BuffsAnalysisDisplay.tsx, src/lib/overlays/drawers/SettingsDrawer.tsx, src/lib/tabs/tabShowcase/RelicScorerTab.jsx, src/types/resources.d.ts
* Added translation for info panel position settings
* Added translation for True/False in info panel
*
=> feat: translate bool in info panel, info panel settings

.github/workflows/drearyquibbles.yml
* Enabled console.* on dreary quibbles
*
=> feat: enable console.* on dreary quibbles

src/lib/tabs/tabShowcase/RelicScorerTab.jsx
=> hotfix: alert border color

src/data/game_data.json, src/lib/conditionals/character/1400/Cipher.ts, src/lib/conditionals/character/1400/Hyacine.ts, src/lib/constants/constants.ts, src/lib/state/metadata.ts, src/lib/tabs/tabShowcase/RelicScorerTab.jsx
=> feat: 3.3v3

src/lib/conditionals/character/1200/Lingsha.ts, src/lib/conditionals/character/8000/TrailblazerRemembrance.ts, src/lib/gpu/wgsl/computeShader.wgsl
* Fix float types
* https://github.com/fribbels/hsr-optimizer/issues/840
Firefox:
Same result in Chrome:
=> fix: shader compilation on ff nightly

src/lib/conditionals/character/1400/Hyacine.ts
=> hotfix: hyacine e2 is a team buff

src/lib/conditionals/character/1400/Cipher.ts, src/lib/constants/constants.ts
=> feat: 3.3v4

src/lib/gpu/webgpuOptimizer.ts, src/lib/optimization/calculateConditionals.ts, src/lib/simulations/contextConditionals.ts, src/lib/simulations/orchestrator/benchmarkSimulationOrchestrator.ts, src/lib/simulations/orchestrator/runCustomBenchmarkOrchestrator.ts, src/lib/simulations/simulateBuild.ts, src/lib/simulations/tests/customBenchmark/benchmarkOrchestrator.test.ts, src/lib/simulations/tests/dpsScore/dpsScoreOrchestrator.test.ts, src/lib/simulations/tests/simDebuggers.ts, src/lib/simulations/utils/benchmarkSpeedTargets.ts, src/lib/tabs/tabBenchmarks/BenchmarksTab.tsx, src/lib/tabs/tabOptimizer/analysis/SubstatUpgrades.tsx, src/lib/worker/optimizerWorker.ts
* Fixing a few spd related benchmark bugs
* Fixing action conditionals for benchmark workers
* Added a SPD dropdown for benchmarks
*
=> fix: various benchmark fixes, spd dropdown selector

src/lib/conditionals/character/1400/Cipher.ts, src/lib/constants/constants.ts
=> feat: 3.3v5

src/lib/overlays/modals/RelicModal.tsx
* Selecting a relic in the relics grid that has less than 4 lines crashes the tab in current beta build
N/A
=> fix: nullable value toString call

public/locales/en_US/optimizerTab.yaml, src/lib/tabs/tabOptimizer/optimizerForm/components/FormSetConditionals.jsx, src/types/resources.d.ts
* Added missing/outdated set conditional descriptions
*
=> feat: update set conditionals wordings

src/lib/state/metadata.ts, src/lib/tabs/tabMetadata/MetadataTab.tsx
* Changed various default teams to use contemporary team compositions
* Added default teams to metadata page
*
=> feat: update default dps sim teams

src/lib/characterPreview/summary/ComboRotationSummary.tsx, src/lib/state/metadata.ts, src/lib/tabs/tabBenchmarks/BenchmarkResults.tsx, src/lib/tabs/tabBenchmarks/benchmarksTabController.ts, src/lib/tabs/tabOptimizer/optimizerForm/components/StatSimulationDisplay.tsx
* Small herta gets err rope
* Fix benchmark crash on non dps
* UI tweaks
* Fill in 2nd relic set on 1st in stat sims
*
=> feat: various qols & fixes

public/locales/en_US/conditionals.yaml, src/lib/conditionals/character/1400/Cipher.ts, src/lib/conditionals/character/1400/Hyacine.ts, src/lib/conditionals/lightcone/5star/LiesAflutterInTheWind.ts, src/lib/conditionals/lightcone/5star/MayRainbowsRemainInTheSky.ts, src/lib/tabs/tabHome/HomeTab.tsx, src/types/resources.d.ts
* Added conditionals descriptions for 3.3 additions
*
=> feat: 3.3 conditionals

src/lib/gpu/webgpuDevice.ts, src/lib/optimization/optimizer.ts, src/lib/simulations/orchestrator/benchmarkSimulationOrchestrator.ts, src/lib/simulations/orchestrator/runCustomBenchmarkOrchestrator.ts, src/lib/simulations/orchestrator/runDpsScoreBenchmarkOrchestrator.ts, src/lib/simulations/tests/customBenchmark/benchmarkOrchestrator.test.ts, src/lib/state/metadata.ts, src/lib/tabs/tabBenchmarks/BenchmarkResults.tsx, src/lib/tabs/tabBenchmarks/BenchmarksTab.tsx, src/lib/tabs/tabBenchmarks/UseBenchmarksTabStore.tsx, src/lib/tabs/tabBenchmarks/benchmarksTabController.ts, src/lib/tabs/tabOptimizer/optimizerForm/OptimizerForm.tsx, src/lib/tabs/tabOptimizer/optimizerForm/components/FormSetConditionals.jsx, src/lib/tabs/tabOptimizer/optimizerForm/components/RecommendedPresetsButton.tsx, src/lib/tabs/tabOptimizer/optimizerForm/components/RelicMainSetFilters.tsx, src/lib/tabs/tabOptimizer/optimizerForm/state/UseFormSetConditionalsDrawer.ts, tests/CharacterPreview/switch-relics-with-character.spec.ts, tests/RelicsTab/add-new-relic.spec.ts
* Adding set conditional drawer to benchmarks tab
*
=> feat: add set conditionals to benchmarks, various fixes

src/lib/characterPreview/CharacterPreview.tsx, src/lib/conditionals/character/1200/March7thImaginary.ts, src/lib/optimization/optimizer.ts, src/lib/tabs/tabShowcase/showcaseTabController.ts, src/lib/tabs/tabWarp/warpCalculatorController.ts
* Addresses #1083 but doesnt solve it
* Fixing March 8th buff not correctly single target
*
=> feat: add warning for gpu permutation cap, fix builds modal

docs/guides/en/benchmark-generator.md, src/lib/tabs/tabBenchmarks/BenchmarksTab.tsx, src/lib/tabs/tabWarp/WarpCalculatorTab.tsx, src/lib/ui/ColorizedLink.tsx
* Adding a title link component
*
=> docs: add benchmark/warp docs link to title

src/lib/overlays/modals/EditImageModal.tsx
* Looks like the old client id stopped working, refreshing it again
* Added docs about how to test
*
=> hotfix: imgur client id

src/lib/importer/importConfig.ts, src/lib/tabs/tabImport/ReliquaryDescription.tsx
=> feat: bump reliquary version

public/locales/de_DE/gameData.yaml, public/locales/en_US/gameData.yaml, public/locales/es_ES/gameData.yaml, public/locales/fr_FR/gameData.yaml, public/locales/id_ID/gameData.yaml, public/locales/it_IT/gameData.yaml, public/locales/ja_JP/gameData.yaml, public/locales/ko_KR/gameData.yaml, public/locales/pt_BR/gameData.yaml, public/locales/ru_RU/gameData.yaml, public/locales/th_TH/gameData.yaml, public/locales/tr_TR/gameData.yaml, public/locales/vi_VN/gameData.yaml, public/locales/zh_CN/gameData.yaml, public/locales/zh_TW/gameData.yaml, src/types/resources.d.ts, tests/CharacterPreview/double-click-to-optimizer.spec.ts, tests/CharacterPreview/switch-relics-with-character.spec.ts
* Update gameData translation files to use new characterId format for buff characters
*
=> fix: i18n buffed character Ids format

src/lib/tabs/tabCharacters/CharacterGrid.tsx, src/lib/tabs/tabCharacters/CharacterTab.jsx
* Fixed character grid not updating when making changes from optimiser tab
*
=> fix: character grid not updating

src/data/game_data.json, src/lib/conditionals/character/1000/Saber.ts, src/lib/conditionals/character/1200/BladeB1.ts, src/lib/conditionals/character/1200/JingliuB1.ts, src/lib/constants/constants.ts
=> feat: 3.4v2

.github/workflows/typecheck.yml, src/lib/gpu/tests/webgpuTestUtils.ts, src/lib/tabs/tabMetadata/MetadataTab.tsx, src/lib/tabs/tabWarp/WarpCalculatorTab.tsx
* Added tsc to CI actions
* proper functioning shown FI00ds/hsr-optimizer#3
=> chore: tsc in ci

src/lib/conditionals/character/1400/Hyacine.ts
* Hyacine e1 teammate toggle was not configured
*
=> fix: hyacine e1 toggle

src/lib/tabs/tabCharacters/CharacterTab.jsx
* Fixes character tab not updating after sorting by score
* Closes #1207
=> hotfix: sort by score not properly updating the grid

src/data/game_data.json, src/lib/conditionals/character/1000/Archer.ts, src/lib/conditionals/character/1000/KafkaB1.ts, src/lib/conditionals/character/1000/Saber.ts, src/lib/conditionals/character/1000/SilverWolfB1.ts, src/lib/conditionals/character/1400/Phainon.ts, src/lib/conditionals/lightcone/5star/ThusBurnsTheDawn.ts, src/lib/constants/constants.ts, src/lib/state/metadata.ts
=> feat: 3.4v3 content

src/lib/characterPreview/ShowcaseCustomizationSidebar.tsx
* Changed the showcase sidebar to properly name downloaded screenshots
*
=> feat: named sidebar downloads

public/locales/de_DE/gameData.yaml, public/locales/en_US/gameData.yaml, public/locales/es_ES/gameData.yaml, public/locales/fr_FR/gameData.yaml, public/locales/id_ID/gameData.yaml, public/locales/it_IT/gameData.yaml, public/locales/ja_JP/gameData.yaml, public/locales/ko_KR/gameData.yaml, public/locales/pt_BR/gameData.yaml, public/locales/ru_RU/gameData.yaml, public/locales/th_TH/gameData.yaml, public/locales/tr_TR/gameData.yaml, public/locales/vi_VN/gameData.yaml, public/locales/zh_CN/gameData.yaml, public/locales/zh_TW/gameData.yaml, src/lib/characterPreview/BuffsAnalysisDisplay.tsx, src/lib/characterPreview/characterPreviewController.tsx, src/lib/rendering/displayUtils.tsx, src/lib/rendering/optionGenerator.ts, src/lib/tabs/tabOptimizer/OptimizerSuggestionsModal.tsx, src/lib/tabs/tabOptimizer/optimizerForm/components/OrnamentsOptions.tsx, src/types/resources.d.ts, tests/CharacterPreview/double-click-to-optimizer.spec.ts, tests/CharacterPreview/switch-relics-with-character.spec.ts
* Changed buff indicator in character names
* Fixed various t function calls to no longer use `as never`
*
=> feat: finalise buff indicators

src/lib/tabs/tabWarp/warpCalculatorController.ts
=> feat: 3.4 warp counts

public/locales/en_US/optimizerTab.yaml, src/lib/i18n/i18n.ts, src/lib/tabs/tabOptimizer/optimizerForm/components/ComboFilter.tsx, src/types/resources.d.ts
* Added spanish to languages available on main page
* To be merged after the current crowdin PR is merged
=> feat: enables es-ES

src/lib/constants/constants.ts
=> feat: 3.4v4 version message

src/data/game_data.json, src/lib/conditionals/character/1000/Archer.ts, src/lib/conditionals/character/1200/BladeB1.ts, src/lib/conditionals/character/1200/JingliuB1.ts, src/lib/conditionals/character/1400/Phainon.ts, src/lib/constants/constants.ts, src/lib/optimization/rotation/preprocessor/preprocessCharacters.ts, src/lib/optimization/rotation/preprocessor/rotationPreprocessor.ts
=> feat: 3.4v5

public/locales/en_US/conditionals.yaml, src/lib/conditionals/lightcone/5star/FlameOfBloodBlazeMyPath.ts
* Changed `FlameOfBloodBlaseMyPath` to automatically evaluate whether or not to apply the additional dmg% boost
*
=> feat: smart mydei sig

src/lib/tabs/tabOptimizer/optimizerForm/components/CharacterSelect.tsx, src/lib/tabs/tabOptimizer/optimizerForm/components/LightConeSelect.tsx
- Fixes character and lc filters not reseting when closing/re-opening the model via the images
-
=> fix: character/lc filters not reseting

src/lib/characterPreview/CharacterCardCombatStats.tsx, src/lib/characterPreview/CharacterStatSummary.tsx, src/lib/conditionals/character/1200/BladeB1.ts, src/lib/state/metadata.ts, src/lib/tabs/tabBenchmarks/benchmarksTabController.ts, src/lib/tabs/tabOptimizer/optimizerForm/components/CharacterSelectorDisplay.tsx
- Silverwolf DPS score initial configs
- Various fixes
-
=> feat: sw dps score / various fixes

public/locales/en_US/conditionals.yaml, src/types/resources.d.ts
- Fixed Phainon E1 not being representative of in game effects
- Fixed inconsistent formatting on Blade E1 label
- Removed `(s)`
-
=> fix: 3.4 conditional wordings

src/lib/conditionals/character/1400/Phainon.ts
- Phainon was missing FUA dmg enabled
-
=> hotfix: phainon fua should be enabled

src/lib/importer/importConfig.ts, src/lib/importer/kelzFormatParser.tsx, src/lib/state/metadata.ts, src/lib/tabs/tabImport/ReliquaryDescription.tsx
- Updating reliquary format to support buffed character imports
-
=> feat: buffed character imports

src/index.tsx, src/lib/state/db.ts, src/lib/state/saveState.ts, src/lib/tabs/tabImport/ScannerImportSubmenu.tsx, src/lib/tabs/tabImport/ScannerWebsocketClient.tsx, src/types/store.ts
- Added the three ingestion state toggles for live import to save state
- N/A
N/A
=> feat: save ingestion state for live imports

src/lib/importer/kelzFormatParser.tsx, src/lib/overlays/modals/RelicRerollModal.tsx, src/lib/tabs/tabImport/ScannerWebsocketClient.tsx
- Moved buff migration responsibility into parseRelic and parseCharacter
- Exposed and used buff migration helpers in live imports logic
=> fix: apply character mappings for live imports

src/lib/overlays/modals/RelicRerollModal.tsx
- Don't call the hook conditionally.
=> fix: conditional hook usage

src/lib/conditionals/character/1400/Cerydra.ts, src/lib/conditionals/character/1400/Hysilens.ts, src/lib/conditionals/lightcone/5star/WhyDoesTheOceanSing.ts, src/lib/constants/constants.ts, src/lib/gpu/injection/injectActionDamage.ts, src/lib/gpu/wgsl/computeShader.wgsl, src/lib/optimization/calculateDamage.ts
=> feat: 3.5v6

src/lib/characterPreview/CharacterCustomPortrait.tsx, src/lib/characterPreview/CharacterPreview.tsx, src/lib/characterPreview/ShowcasePortrait.tsx, src/lib/characterPreview/characterPreviewController.tsx, src/lib/conditionals/character/1100/Bronya.ts, src/lib/constants/constantsUi.ts, src/lib/state/metadata.ts, src/lib/utils/vibrantFork.ts
=> refactor: metadata id updates, kafka subdps, enable bronya e2 default

docs/guides/en/live-import.md, public/locales/en_US/conditionals.yaml, src/lib/conditionals/character/1400/Evernight.ts, src/lib/conditionals/character/1400/PermansorTerrae.ts, src/lib/conditionals/lightcone/5star/InTheNameOfTheWorld.ts, src/lib/conditionals/lightcone/5star/ToEvernightsStars.ts, src/lib/constants/constants.ts, src/lib/gpu/injection/injectConditionals.ts, src/lib/gpu/wgsl/computeShader.wgsl, src/lib/gpu/wgsl/structs.wgsl, src/lib/optimization/config/setsConfig.ts, src/lib/optimization/defaultForm.ts, src/lib/optimization/rotation/comboStateTransform.ts, src/lib/optimization/rotation/setConditionalContent.ts, src/lib/tabs/tabChangelog/ChangelogTab.tsx, src/lib/tabs/tabImport/ImportTab.tsx, src/lib/tabs/tabImport/ScannerImportSubmenu.tsx, src/lib/tabs/tabOptimizer/optimizerForm/components/FormSetConditionals.jsx, src/lib/tabs/tabOptimizer/optimizerForm/components/TeammateCard.tsx, src/lib/tabs/tabShowcase/ShowcaseTab.tsx, src/lib/tabs/tabWarp/warpCalculatorController.ts, src/types/optimizer.ts
=> feat: 3.6v3

src/lib/conditionals/character/1400/PermansorTerrae.ts, src/lib/optimization/rotation/comboStateTransform.ts
- Ashblazing hit split for dhpt
- New sets can stack
-
=> hotfix: new set stacking, dhpt ashblazing

src/lib/importer/hoyoLabFormatParser.tsx
- Changed hoyolab import to automatically detect buff status of novaflare characters
-
=> fix: add automatic buff detection to hoyolab import

src/data/game_data.json, src/lib/conditionals/character/1400/Evernight.ts, src/lib/conditionals/character/1400/PermansorTerrae.ts, src/lib/conditionals/character/8000/TrailblazerRemembrance.ts, src/lib/conditionals/lightcone/5star/ThoughWorldsApart.ts, src/lib/constants/constants.ts, src/lib/state/metadata.ts, src/lib/tabs/tabChangelog/ChangelogTab.tsx, src/lib/tabs/tabOptimizer/conditionals/DisplayFormControl.tsx
=> feat: 3.6v4

index.html
- Bing search is complaining about a missing H1 tag for indexing
-
=> fix: seo indexing issues

src/lib/conditionals/character/1000/Archer.ts, src/lib/conditionals/character/1400/PermansorTerrae.ts, src/lib/tabs/tabChangelog/ChangelogTab.tsx, src/lib/tabs/tabOptimizer/optimizerForm/components/OptimizerOptionsDisplay.tsx
- Archer fua was disabled
- Dhpt teammate ehp should be multiplied by 1 not 0
-
=> fix: archer fua / dhpt teammate ehp / exclude select height

src/lib/optimization/calculateStats.ts, src/lib/state/metadata.ts
- Updating ERR rope metadata
- Kafka's EHR interaction with robin wasnt working because the teammate conditionals happen after the character conditionals. Need a revisit.
-
=> feat: err rope saber / evernight, fix kafka ehr -> atk order
