src/lib/dataParser.js
correcting silver wolf tanky debuffer relic stats weights and adjusting crit > atk for e2+ dps SW
=> Hotfix/Silver Wolf relic stats weights

src/lib/lightConeConditionals.js
Only Silence Remains Crit Rate Passives correction:
S1: 12%
S2: 15%
S3: 18%
S4: 21%
S5: 24%
Reference: https://hsr.yatta.top/en/archive/equipment/21003/only-silence-remains
=> hotfix: Only Silence Remains Light Cone Crit Rate passive

package-lock.json, package.json, src/components/RelicFilterBar.js, src/components/RelicsTab.js, src/lib/db.js, src/lib/renderer.js
Previously, the grade column in the relic table only sorted by grade, even though that is where the "verified" status is also surfaced. This PR adds a custom comparator to enable sorting and filtering by verified status.
=> feat: sort and filter relics by verified status

src/components/RelicModal.js
Hotfix: Main Stat now checks if there's any previous selected main stat when clicking edit relic
- mainStatOptions useEffect now checks if the currently selected relic has already any mainstattype selected to avoid being reset for the mainStatOptions[0] for edit relic modal
Before this change:
When selecting any relic to edit that already has a mainStatType selected:
the modal opens with the mainStatOptions[0] (hp% in this example) as the default selection:
After this change:
When selecting the same relic to edit:
the modal now opens with the previously mainStatType selected (SPD in this example) as the default selection:
Please merge this change back to beta branch, so both will be fixed :)
=> Fix mainStatType selection in RelicModal

src/lib/db.js
Hotfixes the relic delete screen flashing by removing the redraw method.
- Deleted redundant redrawRows() method for relic delete flow.
=> Hotfix: Remove redundant code for redrawing rows in DB.js

src/components/CharacterPreview.js, src/components/OptimizerBuildPreview.js, src/components/OptimizerForm.js, src/components/OptimizerTab.js, src/components/RelicsTab.js, src/components/Tabs.js, src/lib/characterConditionals.js, src/lib/optimizerTabController.js, src/lib/relicModalController.ts, tests/CharacterPreview/delete-character.spec.ts, tests/CharacterPreview/double-click-to-optimizer.spec.ts, tests/CharacterPreview/edit-main-stat-loads-maxed-stat.spec.ts, tests/RelicModal/1-edit-from-optimizer-tab.spec.ts, tests/RelicModal/2-edit-from-character-preview-tab.spec.ts, tests/RelicModal/3-edit-from-relics-tab.spec.ts, tests/RelicsTab/add-new-relic.spec.ts
refactor: tab rendering optimization fixes, update tests with new tab rendering
update tests, update component rerender triggers since tabs dont fully rerender now
Fixed a few bugs from the original rendering refactor. Now most components should update correctly when changes are made across tabs. 
Updated the tests to reflect the new changes - mostly selectors are different since things are not unmounted anymore.
Cleaned up the 'DRY this up (CharacterPreview.js, OptimizerBuildPreview.js, RelicsTab.js)' on onEditOk() 
I think there may still be cases where relic updates don't immediately reflect until the user clicks some stuff but those seem to be minor / rare
=> refactor: tab rendering optimization fixes, update tests with new tab rendering

src/components/CharacterPreview.js, src/components/RelicScorerTab.js
fix: relic scorer tab scrolling to top on swapping characters
The state management in the relic scorer was kinda tied up, causing some weird scrolling behavior. Did a minor refactor and fixed the scrolling and the Divided animation
n/a
animation changes - n/a
=> fix: relic scorer tab scrolling to top on swapping characters

src/components/optimizerTab/Sidebar.js
Added a simple progress bar to be more visual in search optimizer progress.
- Added simple progress bar to reflect the current search/permutation status.
- Changed the optimizer control component to have 550px height to fit the new progress bar.
=> Feature: Add simple progress bar to optimizer search

.github/pull_request_template.md
Removing the `(if applicable)` from screenshot section for PR templates.
- Removed the `(if applicable)` from screenshot section for PR templates
=> removing the (if applicable) from PR screenshot section

src/lib/conditionals/character/Tingyun.tsx
Bugfixes the skill damage increase calculation, skill description and adds the flat lightning dmg to basic atk (only tingyun damaging skill). The skill dmg buff only applies to the flat Lightning dmg buff Benediction provides, with E4 only buffing +20% in this damage, not the atk scaling.
- Add `skillLightningDmgBoostScaling` separately from `skillAtkBoostScaling`
- Add `x.BENEDICTION_LIGHTNING_DMG * x[Stats.ATK]` to `x.BASIC_DMG`
- Fix `skillAtkBoostScaling`
- Tingyun skill description tip
Before:
After:
=> Bugfix: skillAtkBoostScaling calculation and description in Tingyun.tsx

src/components/RelicPreview.js
Fixes rendering when only partially equipped relics for build.
- Fixes the undefined error when accessing `score.meta.modified` prop.
Before:
After:
=> Bugfix: Conditional Rendering in RelicPreview.js

src/lib/workerPool.js
Workers in Vite seem to have a chance to fail to initialize and die silently on Chromium browsers, when too many new workers are created at once. Using some bandaid retry logic while we investigate the root cause
N/A
=> fix: add retry to worker initialization

src/components/ImportTab.jsx, src/lib/conditionals/lightcone/4star/TheBirthOfTheSelf.ts, src/lib/conditionals/lightcone/5star/CruisingInTheStellarSea.ts, src/lib/db.js, src/lib/relicModalController.ts, src/window.d.ts
Various QOLs/fixes:
* Allowing non-relic imports, just update characters in that case
* No longer rejects the file
* Deprecate Fribbels scanner 
* Removing cases where user's input contradicts the enemy options `r.enemyHp50FuaBuff && request.enemyHpPercent < 0.50` 
* Fix bug where character tab didnt update on relic modal OK
https://github.com/fribbels/hsr-optimizer/issues/118
=> qol: clarify enemy hp logic, deprecate fribbels scanner, fix char tab refresh bug

src/components/CharacterModal.jsx, src/components/CharacterTab.jsx, src/components/OptimizerBuildPreview.jsx, src/components/OptimizerForm.jsx, src/components/OptimizerTab.jsx, src/components/optimizerTab/OptimizerGrid.jsx, src/components/optimizerTab/OptimizerOptions.tsx, src/components/optimizerTab/Sidebar.jsx, src/components/optimizerTab/TeammateCard.tsx, src/components/optimizerTab/constants.ts, src/lib/db.js, src/lib/hint.jsx, src/lib/optimizerTabController.js
A couple QOLs:
* Selecting a teammate will auto-load their eidolon/lc/s/sets now
* Added a sync button to re-load the teammate's data
* Fixed edit character modal not loading the right numbers
* Move stat display to the sidebar, small refactor of optimizer stuff to support this
* Cleaned up some more optimizer tab / grid / form rendering. Cut out a bunch of wasted rerenders of the form
* Added an icon to optimize button
https://github.com/fribbels/hsr-optimizer/issues/107
https://github.com/fribbels/hsr-optimizer/issues/108
=> feat: autoload teammate data, sync button, move stat display to sidebar

src/lib/relicScorer.ts, src/types/Relic.d.ts
Previously the free roll given to mainstats were unweighted, which gives false weight to useless mainstats. E.g. a relic with healing boost on argenti would have a nonzero total weight. 
https://discord.com/channels/800607517074784256/1177491834369474570/1208161718014967890
- added weighting to the mainstat free roll
- removed a useless field from relics to try and make them more read-only and less mutable
Fake relics, filtered for Argenti (all stats on the body are 0 value on argenti)
Before:
After:
=> Weight mainstat free roll

src/lib/conditionals/utils.ts
Fix calculation of ashblazingAtk and ashblazingMulti via getting the baseAtk from request instead of c.
- Fixed getting baseAtk from request instead of c.
Before fix:
After fix:
=> Bugfix: Ashblazing FUA bonus calculation

src/components/RelicScorerTab.jsx, src/lib/dataParser.js, src/lib/utils.js
* Adding a scoring character selector sidebar dropdown with unreleased characters
* Clicking it simulates their E0S1, otherwise there's a + for customizing
* Removed the simulate button in favor of the sidebar
=> feat: scorer simulate character sidebar

src/components/optimizerTab/TeammateCard.tsx, src/lib/ocrParserKelz3.js
* 2.0 broke the kelz scanner for S levels and equipped
* Hotfix the S0 light cone imports, default to S1 and level 80s
=> hotfix: S0 light cone imports from scanner

package-lock.json, package.json, src/components/RelicFilterBar.jsx, src/components/RelicsTab.jsx, src/lib/gradient.js, src/lib/hint.jsx, src/lib/relicAugmenter.js, src/lib/relicScorer.test.ts, src/lib/relicScorer.ts, src/types/Relic.d.ts, vite.config.ts
~An aggregated best case column that finds the best case weight across all chars, or just all owned chars~
Refactor relic scoring into the relicscorer file
https://discord.com/channels/800607517074784256/1198367043167195246/1205971445210026054
N/A
- moved relic weight scoring logic into the relicscorer file
- use a DB method to refresh the relic rows, rather than directly calling the grid api
- initialise a constant at load time, rather than with a function
- substat prediction would previously unconditionally add a weight that then gets used by extrarolls...even if there was no spare slot on the relic for a new substat. This would give irredeemably trash relics a spuriously high weight
=> Refactor relic weight scoring into relicScorer

src/components/OptimizerForm.jsx
* Updated default max energy stacks for Today is Another Peaceful Day lightcone depending on the selected character.
* Closes #11
=> Updated default max energy stacks for Today is Another Peaceful Day lightcone

.github/workflows/ci.yml, src/components/optimizerTab/optimizerForm/OptimizerTabCharacterPanel.tsx, src/components/optimizerTab/optimizerForm/RecommendedPresetsButton.tsx, src/lib/db.js, src/lib/utils.js
* Fragment routing has been broken, so hsr-optimizer#scorer redirects back to the homepage. Attempt to fix
* Round up to 100th on speed decimal for preset breakpoint min spd filters
*
=> fix: routing fragments, preset speed decimals

src/lib/constants.ts
Implemented the changes specified by Issue #181. Relic substat ordering in the filter menu change. This PR is under src/lib/constants.ts
=> fix: relic substat ordering

src/components/optimizerTab/optimizerForm/OptimizerOptionsDisplay.tsx
* Added `optionFilterProp='label'` in character exclude select search to use the label for the character instead of the value.
Live beta now:
because it was only filtering by the id value:
After this fix it changes to be the character name:
=> Add optionFilterProp to use label prop in character exclude options

package-lock.json, package.json, src/lib/db.js, src/lib/utils.js
* Changed the img generation library
* Downloads now show images correctly on safari on desktop and mobile
* Fixed bug with character imports not clearing out unreleased characters
* https://github.com/fribbels/hsr-optimizer/issues/208
=> feature: enable mobile/safari scorer image download

src/lib/db.js, src/lib/importer/importConfig.js, src/lib/importer/kelzFormatParser.jsx
* Because the reliquary archiver has accurate decimals, we have to specify that in the kelz format parser
* Unverified -> verified imports should now update correctly for reliquary import
*
=> fix: inherit speed verified status from reliquary importer

src/App.jsx, src/components/MenuDrawer.jsx, src/components/characterPreview/StatRow.tsx, src/lib/conditionals/character/Pela.ts, src/lib/utils.js
* QOLs
* Pela E2 should be off by default
* Show decimals to 1000ths on character tab
* Make menu sidebar sticky
* N/A
=> feat: sticky sidebar, hover stats to show 1000th decimals, fix pela e2 default off

src/components/RelicFilterBar.jsx, src/components/RelicsTab.jsx, src/lib/gradient.js, src/lib/hint.jsx, src/lib/relicScorer.test.ts, src/lib/relicScorer.ts, src/types/Relic.d.ts
* Changed: move from 'optimality' to 'potential'
* Removed: owned chars relic potential
* Added: 'new stats' + 'rolled stats' on hover to the bucket view
* Fix: in certain situations an optimal relic might select an impossible mainstat, it now will not
N/A
=> Aphs potential polish

src/components/RelicsTab.jsx, src/lib/db.js, src/lib/relicModalController.ts
* Fixed assigning the owner of relic during creation, when relic is originally stored
However, I feel that this fix is rather suboptimal, no?
Would it not make more sense to move this kind of consistency work into `DB` itself?
On the other hand, refactoring `DB` (and also moving it to TS, see #44) seems like a lot of work for a (currently) small gain(?).
Although this is my naive view on these things ^^
Edit:
I have found two more issues (both being fixed):
Reproduce:
- Add/import a character
- Add a relic to the character
- Go to the `Characters` screen (to visually see the issue)
- Edit the relic to be of a different part
- The relic should still be visually on the original part, but the score is shown on the new part (see first screenshot)
Reproduce:
- Add/import a character
- Add a …
=> fix: set relic owner correctly on creation

src/components/RelicFilterBar.jsx, src/components/RelicsTab.jsx, src/components/optimizerTab/OptimizerForm.jsx, src/components/optimizerTab/optimizerForm/CardSelectModalComponents.tsx, src/components/optimizerTab/optimizerForm/CharacterSelect.tsx, src/components/optimizerTab/optimizerForm/LightConeSelect.tsx, src/components/optimizerTab/optimizerTabConstants.ts, src/lib/db.js, src/lib/saveState.js, tests/RelicModal/3-edit-from-relics-tab.spec.ts, tests/RelicsTab/delete-relic.spec.ts
* Updated tests with more generic selectors
* Added a multiple select option for character select
* Added filter for custom characters list
* Dont sort relics grid if its already sorted
* Better optimizer start button reponsiveness
* Extract some shared code from LC / Char selectors
* #266
=> feat: potential view with subset of characters

eslint.config.js
React/recommended weren't enabled in the last commit moving to flat ESLint config due to a misconfiguration. 
This PR re-enables it.
=> fix: properly enable React/recommended rules

src/App.jsx, src/components/MenuDrawer.jsx, tests/RelicModal/3-edit-from-relics-tab.spec.ts, tests/RelicsTab/add-new-relic.spec.ts, tests/RelicsTab/delete-relic.spec.ts, tests/TabRender/tab-render.ts, tests/global.setup.ts
- Adds ability to toggle left sidebar open and closed to save screen space
- Adds new icons for the top submenu
- Change subheadings to PascalCase
Adds #274.
Menu, set to be opened on default, with new icons:
Closed menu:
=> Toggle sidebar visibility and minor visual improvements

GETTING_STARTED.md
There is not typically two 0's in the node version here, and nvm-windows (maybe nvm too) complains during install.
* Fix node version format in GETTING_STARTED.md guide. This is the typical version number format.
* Also, the previous string with extra 0 is not supported in nvm-windows (maybe nvm too).
* N/A
=> fix: update node version to 18.19.0; remove extra 0

src/components/characterPreview/StatRow.tsx
* Added a function to detect whether the current speed value in the stat row is within the list of speed breakpoints.
* Changed the stat display behaviour to show the speed value in 1000th decimal place if it is within any of the speed breakpoints.
* Closes #243
=> feat(#243): add 1000th decimal display for certain speeds

src/lib/conditionals/character/Aventurine.ts, src/lib/conditionals/character/BlackSwan.ts, src/lib/conditionals/conditionalConstants.ts, src/lib/conditionals/lightcone/5star/BaptismOfPureThought.ts, src/lib/conditionals/lightcone/5star/WorrisomeBlissful.ts, src/lib/optimizer/calculateDamage.js
* Crit vulnerability implementation in damage formula
* Updated Aventurine ult / Ratio LC / Topaz LC
* Updated black swan e1 to be dot type res pen instead of all type
* N/A
=> hotfix: add crit vulnerability calc to aventurine/topaz lc/ratio lc, black swan e1 res pen elements

src/App.jsx, src/components/Tabs.jsx
* Fixing a bug where the content width bleeds into the sidebar on firefox/opera
* 
Before:
After:
=> fix: content width bleeding into the sidebar

src/components/GettingStartedTab.jsx
* The picture in `Get-Started`/`Step 3: Apply filters` is placed incorrectly. See the Screenshots.
original step 3
modified step 3
=> doc: replace wrong pic in guide

src/lib/characterConverter.ts, src/lib/importer/importConfig.js
* Overriding special relic IDs that have unique set/part mappings. These were generally purples so low impact
* Upgrade reliquary to 0.1.5
=> hotfix: unique relic ids, reliquary version

src/components/optimizerTab/optimizerForm/DamageCalculatorDisplay.tsx, src/components/optimizerTab/optimizerForm/SimulatedBuildsGrid.tsx, src/lib/optimizerTabController.js, src/lib/relicFilters.js, src/lib/statSimulationController.tsx, src/lib/utils.js
* Adding simulated builds import from optimizer
* This imports a selected build a Substat Rolls simulation, filling in the equivalent rolls and main stats and set
* Moved conditional set effects to the grid footer instead of having it in options
* Enabled partial relic sets
* N/A
=> feat: import optimizer builds as simulation

src/components/CharacterTab.jsx, src/components/optimizerTab/FormCard.tsx, src/components/optimizerTab/conditionals/LightConeConditionalDisplay.tsx, src/components/optimizerTab/optimizerForm/EnemyOptionsDisplay.tsx, src/components/optimizerTab/optimizerForm/OptimizerOptionsDisplay.tsx, src/lib/conditionals/character/Boothill.ts, src/lib/statSimulationController.tsx
* Fixed some ui element overflows on small screens/firefox
* Fixed boothill's text causing overflows
* Remove autostart on simulation for imports
* Round sim rolls to 4 precision instead of 5
* 
Before
After
=> fix: ui adjustments for small screens/firefox, boothill text adjustments, dont autostart sim on import

src/components/ChangelogTab.tsx, src/components/MenuDrawer.jsx, src/components/optimizerTab/FilterContainer.tsx, src/components/optimizerTab/FormCard.tsx, src/components/optimizerTab/FormRow.tsx, src/components/optimizerTab/OptimizerForm.jsx, src/components/optimizerTab/Sidebar.jsx, src/components/optimizerTab/conditionals/FormSlider.tsx, src/components/optimizerTab/optimizerForm/CharacterSelectorDisplay.tsx, src/components/optimizerTab/optimizerForm/FormStatRollSlider.jsx, src/components/optimizerTab/optimizerForm/OrnamentSetTagRenderer.tsx, src/components/optimizerTab/optimizerForm/RecommendedPresetsButton.tsx, src/components/optimizerTab/optimizerForm/RelicMainSetFilters.tsx, src/components/optimizerTab/optimizerForm/RelicSetTagRenderer.tsx, src/components/optimizerTab/optimizerForm/SimulatedBuildsGrid.tsx, src/components/optimizerTab/optimizerForm/StatSimulationDisplay.tsx, src/components/optimizerTab/optimizerForm/SubstatWeightFilters.tsx, src/components/optimizerTab/optimizerForm/TeammateCard.tsx, src/components/optimizerTab/optimizerTabConstants.ts, src/lib/conditionals/character/Sparkle.ts, src/lib/constants.ts, src/lib/db.js, src/lib/defaultForm.js, src/lib/hint.jsx, src/lib/optimizer/optimizer.js, src/lib/statSimulationController.tsx
* Changed sparkle skill on self to default to false
* Calculate the pinned top row when simulations are run
* Sort the autogenerated stats summary for simulator by damage stats first
* Fixed some messed up widths on the optimizer page
* Set a max width on the changelog images
* Fix form container border taking up 2 extra px
* Renamed menu header Menu -> Optimization 
* Rename simulation filter row to Character custom stats simulation
*
=> feat: stat simulator QOLs, optimizer width adjustments, fix sparkle skill default

src/App.jsx, src/components/optimizerTab/conditionals/FormSlider.tsx, src/lib/relicScorer.ts, tests/CharacterPreview/switch-relics-with-character.spec.ts
* Fixed a bug that applied to sparkle/bronya's spheres main stat free roll mainly
* Fixed the margin issues from last commit
* Fixed some spacing issues for form input
*
=> fix: main stat free roll was incorrect for cases where the optimal main wasnt at 1 weight

src/components/ChangelogTab.tsx, src/components/optimizerTab/optimizerForm/SimulatedBuildsGrid.tsx, src/components/optimizerTab/optimizerForm/StatSimulationDisplay.tsx, src/lib/characterConverter.ts, src/lib/conditionals/character/Jade.ts, src/lib/conditionals/character/Robin.ts, src/lib/conditionals/conditionalConstants.ts, src/lib/conditionals/lightcone/5star/YetHopeIsPriceless.ts, src/lib/optimizer/calculateDamage.js, src/style/style.css
* Turn off dmg boosts (salsotto) for robin ult dmg
* Fix wording on Yet Hope is Priceless
* Remove Jade skill dmg 
* Remove grid header which was disappearing randomly
* Changelog wording
*
=> hotfix: 2.3 wording, remove jade skill dmg, fix grid styling, robin ult boosts

src/lib/characterScorer.ts, src/lib/dataParser.js
* Uncapping the sim SPD substats
* Adding a SPD scaling component by multiplying the score by (1 + spd / baseline spd)
*
=> feat: adding a speed scaling component to the damage sim

src/components/optimizerTab/optimizerForm/TeammateCard.tsx
* When teammates are changed after they're loaded, a potentially null relic is processed in subsequent sync, filter out the null ones
*
=> hotfix: crash when syncing a missing relic slot on a changed teammate after initial sync

src/App.jsx, src/components/LayoutHeader.tsx, src/components/LayoutSider.tsx, src/components/MenuDrawer.jsx, src/components/SettingsDrawer.tsx, src/components/optimizerTab/Sidebar.jsx, src/style/style.css
* permutations sidebar now changes into a fixed footer when screens are 992px < [screen resolution] < 1530px
* add new screen breakpoint at 1530px
* reduce the left padding on `LayoutSider` menu items: this may need a discussion. Basically, antd applies a single CSS class with extra left padding when there is only "one" item within a subitem menu, preventing any use of it being overridden even with `inlineIndent` prop. Due to the structure of our current menu items, antd views every single submenu option as "one" item and forces extra padding on it. Aside from removing the CSS class scoped exclusively for this purpose, the alternative would be fake-inserting extra phantom tags to wrap around each menu item instead of the `<Flex>menu item contents like the icon + label</Flex>` that is …
=> feat: make permutations sidebar and main menu sidebar responsive

src/lib/dataParser.js
* Add better welt scoring sets
* Remove SPD as substats, add in missing BE
*
=> fix: welt incorrect bis sets

src/components/characterPreview/CharacterScoringSummary.tsx, src/lib/characterScorer.ts, src/lib/dataParser.js
* Penalty multiplier was too harsh for kafka, update it to 1% per missing roll
* Change seele default set to glamoth
*
=> feat: hotfix seele set -> glamoth, nerf penalty multiplier

src/components/CharacterPreview.jsx, src/components/characterPreview/CharacterScoringSummary.tsx, src/lib/characterScorer.ts, src/lib/dataParser.js
* Made sim set effects more lenient with similar sets
* Added BIS set score upgrade to the card
* Methodology docs update
*
=> hotfix: set equivalency and set effects upgrade display

src/components/CharacterPreview.jsx, src/components/characterPreview/CharacterScoringSummary.tsx, src/components/characterPreview/CharacterStatSummary.tsx, src/lib/characterScorer.ts, src/lib/constants.ts, src/lib/constantsSession.ts, src/lib/db.js, src/lib/optimizer/optimizerUtils.js, src/lib/statCalculator.js
* Previously non full builds defaulted to character score, force it to dps score
* Adding option to select previous scoring type
* #376
=> hotfix: allow non full builds for dps score, change contrast color, choose scoring type

src/components/characterPreview/CharacterScoringSummary.tsx
Reorders the rotation formula for character tab to be consistent with optimizer rotation formula order.
* Just inverting the FUA with DOT markers to be equal to the character formula tab.
###Before
Character Tab:
Optimizer Tab:
Character Tab:
Optimizer Tab:
=> Chore: Reordering Rotation Formula

src/components/characterPreview/CharacterScoringSummary.tsx, src/lib/conditionals/character/Aventurine.ts, src/lib/optimizer/calculateBuild.js, src/lib/optimizer/calculateDamage.js, src/lib/optimizer/calculateStats.js, src/lib/worker/optimizerWorker.js, src/types/Conditionals.d.ts
* Fixing a bug where Crit sets were applying before calculateBaseMultis. This meant that in some scenarios, salsotto for example would not activate for aventurine unless his base CR was > 50%. 
* Now we calculate in this order, where crit passives and boost passives from sets are calculated in calculatePostBaseSetEffects, which gain the benefit of being after calculateBaseMultis so that aventurine's trace can apply first.
```
calculateComputedStats(c, request, params)
calculateBaseMultis(c, request, params)
calculatePostBaseSetEffects(c, request, params)
calculateDamage(c, request, params)
```
*
=> hotfix: bug in post-calculateBaseMultis set effects not activating

src/lib/relicScorer.ts
* If the user selects 0 valid mainstats and there are no possible substats of equal weight to the highest weight possible non-substat mainstat, the mainstat would not be assigned
* Changed scoreOptimalRelic to assign an initial mainstat to prevent aforementioned issue
*
=> fix: ensure mainstat is always assigned

src/components/CharacterPreview.jsx, src/components/characterPreview/CharacterScoringSummary.tsx, src/components/optimizerTab/OptimizerForm.jsx, src/components/optimizerTab/optimizerForm/FormStatRollSlider.jsx, src/components/optimizerTab/optimizerForm/RecommendedPresetsButton.tsx, src/components/optimizerTab/optimizerForm/SubstatWeightFilters.tsx, src/lib/characterScorer.ts, src/lib/conditionals/lightcone/5star/CruisingInTheStellarSea.ts, src/lib/db.js, src/lib/defaultForm.js, src/lib/optimizerTabController.js, src/lib/relicFilters.js, src/style/style.css
* Permute main stats on sphere for max sim
* Disable Cruising in the stellar sea CR buff by default
* Cut out some wasted sim runs
* New optimizer substat weight min rolls filter
*
=> feat: scoring update, simulate perfect sphere, fix cruising lc sim, min rolls filter

src/components/optimizerTab/optimizerForm/OptimizerOptionsDisplay.tsx, src/lib/optimizerTabController.js, tests/CharacterPreview/double-click-to-optimizer.spec.ts
* Reorganizing/rename the main stat upscale text
* Set to +15 default
*
=> feat: adjusting main stat upgrade text and fixing it to +15 default

src/lib/importer/kelzFormatParser.jsx
* LC search will prefer direct key matching for all trailblazer builds, the same behavior as searching for other characters. This will fix the issue of the same LC being used across all builds seen in the linked issue. The previous `.startsWith()` search is left in place as a fallback to prevent the current state from degrading further
* Without appropriate breaks (in this case early returns) the current `getTrailblazerId()` implementation will always fall through to the final matching current path regardless of name. This results in duplicate builds as seen in the screenshot below
Closes #416
=> fix (kelzFormatParser): TB id lookup and TB LCs

src/lib/characterScorer.ts
* Currently if HMC is on the team, the sim has trouble deciding between crit builds and BE builds. We need to allow break rope on characters that dont necessarily want break by default if hmc is there.
* Add Iron Cavalry as acceptable set option too for super break teams
*
=> hotfix: add BE link rope and cavalry set to simulation if break effect team

src/lib/dataParser.js, src/lib/relicScorer.ts, src/lib/utils.js
* Fix the relics tab bug where invalid/suboptimal stats were being used for displaying on hover. 
* Added the correct filtering logic for valid upgrades, and the weight comparison for new substats should be based on the max score not min score.
* Fixed Firefly's sim main stats, added Fire DMG for gallagher sphere
* #433
=> fix: relics tab invalid upgrades bug

misc/beta/data.ts, package-lock.json, package.json, src/components/RelicFilterBar.jsx, src/components/RelicsTab.jsx, src/lib/relicScorer.ts
* Fixing a bug where no stats are showing for upgrades when non 1 weight is max
*
=> fix: candidate stat generation should use best available substat weight

src/components/RelicsTab.jsx, src/components/optimizerTab/optimizerForm/CharacterSelect.tsx
I added "All" and "None" buttons to the character selection screen. Please review my work, as I am unsure if I did it correctly. These buttons work with the Element and Path filters, only affecting the visible characters.
Closes #444
=> Added All and None buttons to character select screen.

src/components/CharacterPreview.jsx, src/components/CharacterTab.jsx, src/components/optimizerTab/optimizerForm/CardSelectModalComponents.tsx, src/components/optimizerTab/optimizerForm/CharacterSelect.tsx, src/components/optimizerTab/optimizerForm/LightConeSelect.tsx, src/lib/db.js, src/style/style.css
* Added a searchbar and element/path filters to the top of the character tab
* Closes #406
=> feat: Character tab improvements

src/components/CharacterPreview.jsx, src/lib/optimizer/calculateBuild.js
* Fixing a bug where empty sets were detected as space sealing station. Correcting it by selecting unused sets for empty set slots
* Fixing a bug where empty sets on the sim score card were using their +15 main stats for hands/head
* #447
=> hotfix: bug where empty sets were being calculated incorrectly in optimizer top row

src/components/characterPreview/CharacterScoringSummary.tsx, src/lib/db.js, src/lib/defaultForm.js, src/lib/optimizer/calculateStats.js
* Duran in beta was capped at 6 instead of 5, fixing some users saves that were using that 6 value
* Setting the default for duran to 5 stacks by default
*
=> hotfix: duran beta cap, change default to 5

src/components/optimizerTab/Sidebar.jsx, src/lib/utils.js
* Added a simple time estimate to the optimiser sidebar
* Closes #385
=> feat: estimated time remaining

src/lib/characterScorer.ts, src/lib/conditionals/character/Lingsha.ts, src/lib/conditionals/character/TrailblazerHarmony.ts, src/lib/dataParser.js, src/lib/optimizer/calculateBuild.js, src/lib/optimizer/calculateConditionals.js, src/lib/optimizer/calculateTeammates.js, src/lib/worker/optimizerWorker.js, src/types/CharacterConditional.d.ts
* Fixing a couple bugs:
* Lingsha not interacting correctly with weakness break override from teammates. Add a postPrecompute step to handle
* Teammates without light cones were getting the main character's light cone conditionals
* Feixiao's 130 base spd messing with sim scoring decision on spd vs atk boots. Change decision to base + trace + 25 spd
*
=> hotfix: lingsha break override and feixiao spd boots scoring

src/lib/characterScorer.ts
* When the sim set is nonequivalent, the baseline was using the user's set while the benchmarks were using the top sim set. Fixed the baseline to also use the top sim set.
* This was causing issues because the baseline CR is used to cap the upper limit on CR rolls
Before (cr)
After (cr)
*
=> fix: baseline sim was using the wrong sets for nonequivalent set comparisons

src/lib/characterScorer.ts
* There was a bug where Yanqing's crit passive overflowed the crit rate roll cap here. We should make the min missing crit 0 when that happens
*
=> hotfix: set min missing crit rate to 0 for sim stat roll limits

src/lib/db.js, src/lib/importer/importConfig.js
- hotfix: bug where importing relics overwrites equippedby
- feat: bump kelz scanner version
* Closes https://github.com/fribbels/hsr-optimizer/issues/464
=> hotfix: import relics no longer overwrites equippedBy, bump kelz scanner version

src/components/characterPreview/CharacterScoringSummary.tsx, src/lib/dataParser.js
* Update Moze to 4p pioneer default
* Reducing damage improvements to 4 rows
*
=> hotfix: adjust moze sets, change stat improvements to 4 rows

src/components/CharacterPreview.jsx, src/components/characterPreview/CharacterStatSummary.tsx
* Added CV back
* Added some rules for showing stats, hiding < 64.8 CV, hiding 0% healing boost
* Adjusting the flex display in the center
*
=> hotfix: smarter stat display rules, flex the card center section 

src/components/RelicFilterBar.jsx, src/components/RelicModal.tsx, src/lib/relicModalController.ts
* When relics are modified, they now rescore themselves and updates the grid
* Fixed bug with NaN relic substat value inputs
* Closes https://github.com/fribbels/hsr-optimizer/issues/462
=> feat: rescore relic on modification

src/components/CharacterModal.jsx, src/components/CharacterPreview.jsx, src/components/characterPreview/CharacterScoringSummary.tsx, src/components/characterPreview/StatRow.tsx, src/components/characterPreview/StatText.tsx, src/lib/constants.ts, src/lib/constantsSession.ts, src/lib/dataParser.js, src/lib/db.js, src/lib/utils.js
* Update teammate character modal's LC initial character so it preloads the path
* Update kafka / swan to lean towards DOT over crit in sims
* Add combat stats panel / selector for sim scoring card
*
=> feat: combat stats panel for scoring card

src/components/importerTab/ReliquaryDescription.tsx, src/lib/importer/importConfig.js
* Update reliquary output to v4, scanner version still stuck at 0.1.8 scanner
*
=> hotfix: update reliquary to v4, still 0.1.8 output for now

src/components/characterPreview/CharacterScoringSummary.tsx, src/components/characterPreview/CharacterStatSummary.tsx
* Fix character cards overflowing from combat stats on break units
Before: 
After:
*
=> hotfix: prevent character card overflow

src/components/RelicsTab.jsx
* On the RelicsTab
* Prevent edit relic when relic not selected, display a 'relic not selected' user message.
* Prevent delete confirmation popup from showing if no relic is selected.
* None
=> feat: pevent edit relic when relic not selected & only show relic delete confirm when relic selected

src/components/RelicsTab.jsx
Motivation to be able to select and delete all the ropes I just salvaged.
* Enabled ability to select multiple relics on the relicsTab page using CTRL and SHIFT.
* Added a selectedRelics var to hold selected relics.
* Changed Edit/Delete Relic buttons to enable/disable depending on number of relics selected.
* Changed the Delete button Popconfirm message to show number of relics selected.
* Changed the deletePerform function to delete multiple selected relics.
* ~~Removed feature, arrowKeyGridNavigation. It was conflicting with multiple select by selecting rows instead of navigating.~~
* None
=> feat: select and delete multiple relics

src/components/optimizerTab/Sidebar.jsx, src/components/optimizerTab/optimizerForm/CharacterSelectorDisplay.tsx, src/lib/defaultForm.js, src/lib/gpu/webgpuInternals.ts, src/lib/gpu/webgpuOptimizer.ts, src/lib/optimizer/optimizer.ts, src/lib/optimizerTabController.js
* Added results limit selector, defaults to 1024
*
=> feat: add top-n results selector for gpu optimizer

src/components/RelicScorerTab.jsx, src/components/optimizerTab/optimizerForm/RecommendedPresetsButton.tsx, src/lib/dataParser.js, src/lib/defaultForm.js
* Valorous is now off by default and enabled with a flag
* Activated prisoner set on Jiaoqiu by default
* Various ashblazing default tweaks
*
=> feat: disable valorous by default and enable on certain characters, fix ashblazing counts, jiaoqiu prisoner

src/components/RelicScorerTab.jsx, src/components/optimizerTab/OptimizerForm.jsx, src/components/optimizerTab/optimizerForm/RelicSetTagRenderer.tsx, src/components/optimizerTab/optimizerForm/ResultFilters.tsx
* Hiding the ratings filters since those are rarely used, hidden into an expandable
* Remove closable on relic filters bc it doesnt work
*
=> feat: hide rating filters into collapse

src/lib/characterScorer.ts
* Fixing bug with SPD boots being forced, removing that restriction and adding a limit on speed rolls for an acceptable sim
Before:
After: 
*
=> fix: disable force-spd-boots scoring to fix kafka

src/components/characterPreview/CharacterScoringSummary.tsx
=> fix: correctly display 0 mainstats in DPS summary

src/components/optimizerTab/optimizerForm/RecommendedPresetsButton.tsx
In the Character Optimizer tab, the 'Weighted Rolls per Relic' values reset to 0 upon selecting a recommended preset. The code has now been updated to preserve user-set values. This looked like the original intent of the code.
=> [Bug] Weighted rolls per relic values not preserved

public/locales/en/importSaveTab.json, src/components/importerTab/ClearDataSubmenu.tsx, src/components/importerTab/ImportTab.jsx, src/lib/i18n.ts, src/types/resources.d.ts
* Fixed import tag text
* Modified capitalize formatter to uppercase first letter of string if length not specified
*
=> fix: capitalization typing

docs/guides/en/dps-score.md, docs/guides/en/stat-score.md, src/components/optimizerTab/optimizerForm/FormSetConditionals.jsx, src/lib/characterScorer.ts, src/lib/dataParser.js, src/lib/optimizer/rotation/setConditionalContent.ts
* Sacerdos should be a selector/partition
* Move scoring docs into md files
* Update equivalents sets for scholar/sacerdos - some new BIS
*
=> feat: documentation migration, change sacerdos to a selector in advanced rotations, equivalent sets

docs/guides/en/dps-score.md, src/components/CharacterPreview.jsx, src/components/characterPreview/CharacterScoringSummary.tsx, src/components/optimizerTab/conditionals/LightConeConditionalDisplay.tsx, src/lib/characterScorer.ts, src/lib/dataParser.ts, src/lib/relicScorerPotential.ts
* On-hit stats were missing from combat stats preview
* Light cone conditionals header was accidentally removed
* Fix sunday CR overcap scoring
* Give fugue 3 breaks for scoring, add atk boots
* Fix crash with empty relic
* Add AEON tier dps scoring
*
=> fix: various scoring bug fixes

src/lib/characterPreview/ShowcaseDpsScore.tsx, src/lib/tabs/tabCharacters/CharacterTab.jsx
* Changed character tab grid to accomodate for PT on chromium
* Added name splitting by `-` alongside `•`
* Changed team selector in character card to avoid truncating labels
*
=> fix: character tab sizing

src/lib/characterPreview/CharacterScoringSummary.tsx, src/lib/interactions/notifications.tsx, src/lib/state/metadata.ts, src/lib/tabs/tabHome/HomeTab.tsx
* Banana default for topaz / jing yuan
* Remove the i18n announcement banner
* Fix uuid input clear button
*
=> feat: banana defaults for summoners, some ui tweaks

public/locales/en/common.yaml, src/lib/characterPreview/CharacterPreview.tsx, src/lib/characterPreview/CharacterPreviewComponents.tsx, src/lib/characterPreview/CharacterScoringSummary.tsx, src/lib/characterPreview/ShowcaseLightCone.tsx, src/lib/characterPreview/ShowcasePortrait.tsx, src/lib/characterPreview/ShowcaseStatScore.tsx, src/lib/tabs/tabRelics/RelicPreview.tsx, src/lib/utils/colorUtils.ts, src/style/style.css
* Updated showcase borders, background colors
* Shrink character score text slightly
* Converted elemental damage types to "DMG %" on upgrades panel as some would overflow
* Brighten showcase white text slightly
*
=> feat: showcase ui adjustments

src/lib/tabs/tabOptimizer/optimizerForm/components/EnemyConfigurationsDrawer.tsx
* Effect RES / Dmg RES labels were swapped by accident, changing them back
*
=> hotfix: effect res and dmg res labels were swapped

public/locales/en_US/conditionals.yaml, src/lib/conditionals/character/1300/BlackSwan.ts
* Swan's E4 never got updated after Effect RES implementation, adding 10% team toggle
*
=> fix: swan e4 missing toggle effect

src/lib/tabs/tabRelics/relicPreview/RelicStatText.tsx
* Fixed relic stat text using 2 letter locale codes
* 
before:
after:
=> fix: relicStatText international formatting

public/locales/en_US/conditionals.yaml, src/types/resources.d.ts
* Fixed conditional ocntent text being inconsistent in adding `E1`/`E2`/`E4`/`E6` prefixes for conditionals relating to the Eidolon alone
*
=> fix: consistent eidolon prefix in conditionals

src/lib/characterPreview/ShowcaseCustomizationSidebar.tsx, src/lib/tabs/tabHome/HomeTab.tsx, src/lib/tabs/tabWarp/WarpCalculatorTab.tsx, src/lib/tabs/tabWarp/warpCalculatorController.ts, src/lib/utils/colorUtils.ts, src/style/style.css
* Making it easier to update the income options, adding 3.1 income
* Home tab Search bar swap
*
=> refactor: warp tab cleanup, add 3.1 income options

src/lib/conditionals/character/1400/Aglaea.ts
* Fixed Aglaea speed stack limit to increment at E4 instead of E5
*
=> hotfix: Aglaea speed stacks increments at E5 instead of E4

src/lib/gpu/conditionals/setConditionals.ts
* Fleet of the Ageless was using the wrong method to calculate memo base atk
*
=> fix: broken fleet of the ageless conditional

src/hooks/useDelayedProps.ts, src/lib/characterPreview/CharacterPreview.tsx, src/lib/characterPreview/CharacterPreviewComponents.tsx, src/lib/characterPreview/ShowcaseBuildAnalysis.tsx, src/lib/tabs/tabRelics/RelicPreview.tsx, src/lib/tabs/tabRelics/relicPreview/GenerateStat.tsx
* Added a useDelayedProps hook
* Delaying render of showcase analysis so the card goes faster
* Cleaning up the broken showcase memo logic
* Remove redundant Text tags
*
=> feat: delay and memoize showcase analysis for faster card render

src/lib/tabs/tabOptimizer/analysis/expandedDataPanelController.ts, src/lib/tabs/tabOptimizer/optimizerForm/components/TeammateCard.tsx
* Sacerdos 2x was removed by mistake for sparkle
* Fix a call on null optimizer grid for pinned data on startup
*
=> fix: sparkle sacerdos, null optimizer grid startup

public/locales/en_US/charactersTab.yaml, src/lib/characterPreview/CharacterScoringSummary.tsx, src/lib/characterPreview/summary/DpsScoreMainStatUpgradesTable.tsx, src/lib/characterPreview/summary/DpsScoreSubstatUpgradesTable.tsx, src/lib/optimization/rotation/comboStateTransform.ts, src/lib/scoring/characterScorer.ts, src/lib/scoring/simScoringUtils.ts, src/lib/state/metadata.ts, src/lib/tabs/tabOptimizer/analysis/StatsDiffCard.tsx, src/lib/tabs/tabOptimizer/analysis/SubstatUpgrades.tsx, src/style/style.css, src/types/resources.d.ts
* Adding main / sub upgrade displays, including negatives
*
=> feat: main / sub stat upgrade charts on showcase

src/lib/gpu/injection/generateWgsl.ts, src/lib/gpu/webgpuInternals.ts
* I added some optimizations to suppress unnecessary calculations for the combo but forgot filters need them, inject the suppression only if filters are default
*
=> hotfix: gpu filters should unsuppress their corresponding calculations

src/lib/optimization/context/calculateContext.ts
* Light cone superimposition stats should deactivate on path mismatch
*
=> hotfix: light cone superimposition stats should deactivate on path mismatch

src/lib/optimization/config/setsConfig.ts, src/lib/overlays/modals/ScoringModal.tsx, src/lib/relics/relicFilters.ts, src/lib/state/db.ts, src/lib/tabs/tabOptimizer/optimizerForm/layout/FormCard.tsx
* Pioneer / Wastelander should be on-hit stat boosts not buffs
* Cap weights at [0, 1]
* Update score modal
*
=> feat: cap scoring weights at [0, 1], clean up scoring modal, fix relic set stat boosts

src/lib/relics/relicRollGrader.ts
* Fixing an issue where verified relics with incorrect rolls counts were causing invalid est tbp results.
* The roll counts should add up to the stat value on the relic, so validate it before skipping otherwise recount the rolls with the heuristsic
*
=> fix: inaccurate verified roll counts should be verified before running est tbp

src/lib/tabs/tabOptimizer/combo/comboDrawerController.tsx, src/lib/tabs/tabOptimizer/optimizerForm/OptimizerForm.tsx
* Bug report: https://discord.com/channels/800607517074784256/1189053007741067294/1364420228704108707
* Caused by the stored combo state in DB overwriting the form's combo abilities. Passing in the full form to preserve the combo but needs a followup investigation about the rest of the fields too
*
=> hotfix: stored combo state's abilities shouldnt overwrite form abilities

src/lib/characterPreview/CharacterCardCombatStats.tsx, src/lib/characterPreview/CharacterScoringSummary.tsx, src/lib/characterPreview/ShowcaseBuildAnalysis.tsx, src/lib/characterPreview/summary/DpsScoreMainStatUpgradesTable.tsx, src/lib/characterPreview/summary/SubstatRollsSummary.tsx, src/lib/conditionals/character/1300/Gallagher.ts, src/lib/scoring/dpsScore.ts
* Gallagher skills were on by default for the e2 res buff, disabling
* Adding set upgrades to main stats chart now that the toggle is gone
* Various display tweaks
*
=> feat: add set upgrades to main upgrades, disable gallagher skill default, display tweaks

src/lib/characterPreview/summary/EstimatedTbpRelicsDisplay.tsx, src/lib/characterPreview/summary/statScoringSummaryController.ts, src/lib/optimization/defaultForm.ts, src/lib/overlays/modals/ScoringModal.tsx, src/lib/relics/relicScorerPotential.ts, src/lib/simulations/orchestrator/runCustomBenchmarkOrchestrator.ts, src/lib/simulations/orchestrator/runDpsScoreBenchmarkOrchestrator.ts, src/lib/simulations/tests/customBenchmark/benchmarkOrchestratorTestUtils.ts, src/lib/tabs/tabBenchmarks/BenchmarkResults.tsx, src/lib/tabs/tabBenchmarks/BenchmarksTab.tsx, src/lib/tabs/tabBenchmarks/UseBenchmarksTabStore.tsx, src/lib/tabs/tabBenchmarks/benchmarksTabController.ts
* `mainstatBonus` and `mainstatDeduction` were swapped for current potential
* Reroll avg was using max rolls instead of mid rolls
* Enemy default eff res 20% -> 30%, mostly affects black swan to get her closer to 120% ehr
* Resetting scoring algorithm no longer resets teams
* Add subdps options to custom benchmarks
* Fixing est tbp caching issues
*
=> feat: subdps benchmarks, eff res default 30%, est tbp refresh fixes, current potential bug, reroll avg calculation

src/lib/characterPreview/CharacterCustomPortrait.tsx, src/lib/characterPreview/CharacterPreview.tsx, src/lib/characterPreview/ShowcasePortrait.tsx, src/lib/characterPreview/characterPreviewController.tsx, src/lib/constants/constantsUi.ts
- Added some math to scale dps score portraits by height, since the LC covered some of the image before
- Closes https://github.com/fribbels/hsr-optimizer/issues/1251
=> feat: scale dps score custom portraits by lc height difference

src/lib/characterPreview/CharacterCustomPortrait.tsx
- Forgot to add a vertical scaling limit
-
=> fix: portrait scaling underflow check should account for vertical limit

src/lib/state/db.ts
- When merging new relics into the DB, prefer the id of the new relic if it is verified. This allows old optimizer saves with generated uuids to be replaced by the authoritative id from the game when using live import.
=> fix: prefer imported id when relic is verified

src/lib/scoring/simScoringUtils.ts, src/lib/worker/computeOptimalSimulationWorker.ts
…lens
// Manual adjustment for Hysilens scoring - Using non-EHR light cones forces the benchmark to be unable to hit 120%
// EHR due to diminishing returns. To fix, relax diminishing returns on non-EHR LC builds
See: https://www.reddit.com/r/HysilensMainsHSR_/comments/1mua165/first_time_getting_such_rating/
-
=> hotfix: custom diminishing returns formula on non-ehr light cone hysilens

src/lib/simulations/orchestrator/benchmarkSimulationOrchestrator.ts, src/lib/tabs/tabChangelog/ChangelogTab.tsx
- With DHPT on the team, benchmarks should match banana set
-
=> feat: benchmark set matching for dhpt + banana set

src/lib/importer/hoyoLabFormatParser.tsx
- Fixed hoyolab import not correcting relic equippedBy id when importing buffed characters
-
=> fix: hoyolab import doesn't equip bufffed characters relics
